#pragma kernel Main

Texture2D<float4> Color;
Texture2D<float> Depth;
Texture2D<uint> IDSegMap;

struct FCPixel
{ 
	float4 color;
	float depth;
	float id;
};

RWStructuredBuffer<FCPixel> Output;

[numthreads(8,8,1)]
void Main (uint3 id : SV_DispatchThreadID)
{
	uint w, h;
	Color.GetDimensions(w, h);

	if (id.x >= w || id.y >= h)
		return;
	
	FCPixel data;
	data.color = float4(Color[id.xy].rgb, 0);
	data.depth = Depth[id.xy];
	data.id = asfloat(IDSegMap[id.xy]);
	
	Output[id.y * w + id.x] = data;
}