// This source file was generated by AI and was not human-generated.
using System;
using System.Collections.Generic;
using UnityEngine;

#if UNITY_EDITOR
using UnityEditor;
#endif

[ExecuteAlways]
public sealed class DVM_DroneCamera : DVMotion {
	// Prevents invalid settings from producing an unbounded cache build.
	private const double MaximumCacheSimulationSeconds = 600.0;

	#region Types

	public enum TimeMode {
		AutomaticPreview,
		ManualDeterministic
	}

	[Serializable]
	public sealed class PidSettings {
		[Min(0f)] public float proportional = 3.5f;
		[Min(0f)] public float integral = 0.05f;
		[Min(0f)] public float derivative = 2.4f;
		[Min(0f)] public float integralLimit = 5f;
		[Min(0f)] public float derivativeResponse = 20f;
	}

	private sealed class PidController {
		private readonly PidSettings settings;
		private float integral;
		private float previousError;
		private float derivative;
		private bool initialized;

		public PidController(PidSettings settings) {
			this.settings = settings;
		}

		public float Update(float error, float dt) {
			if (dt <= 0f)
				return 0f;

			if (!initialized) {
				initialized = true;
				previousError = error;
			}

			integral = Mathf.Clamp(
				integral + error * dt,
				-settings.integralLimit,
				settings.integralLimit);

			float rawDerivative = (error - previousError) / dt;
			float blend = 1f - Mathf.Exp(-settings.derivativeResponse * dt);
			derivative = Mathf.Lerp(derivative, rawDerivative, blend);
			previousError = error;

			return settings.proportional * error
				 + settings.integral * integral
				 + settings.derivative * derivative;
		}
	}

	private struct SimulationState {
		public Vector3 position;
		public Quaternion rotation;
		public Vector3 velocity;
		public Vector3 angularVelocity;
		public Vector2 lean;
		public float pathDistance;
		public Vector3 splineTarget;
		public double time;
	}

	[Serializable]
	private struct FlightSample {
		public double time;
		public Vector3 position;
		public Quaternion rotation;
		public Vector3 velocity;
		public Vector3 splineTarget;
		public float pathDistance;
	}

	#endregion

	#region Serialized Configuration

	[Header("Path")]
	[Tooltip("Ordered world-space control points used to construct a Catmull-Rom spline.")]
	[SerializeField] private List<Vector3> pathPoints = new List<Vector3>();
	[SerializeField] private bool closedLoop;
	[Min(0f)] [SerializeField] private float lookAheadDistance = 4f;
	[Range(4, 128)] [SerializeField] private int splineSamplesPerSegment = 24;
	[SerializeField] private bool preventBackwardProgress = true;

	[Header("Initial State")]
	[SerializeField] private Vector3 initialVelocity;

	[Header("Cache")]
	[Tooltip("Time spent hovering around point 0 before path traversal starts.")]
	[Min(0f)]
	[SerializeField] private float startupHoverTime;

	[Tooltip("Time spent hovering around the final point after traversal completes.")]
	[Min(0f)]
	[SerializeField] private float endingHoverTime;

	[Tooltip("Numerical tolerance for considering the closest point to have reached the path end.")]
	[Min(0.0001f)]
	[SerializeField] private float pathCompletionTolerance = 0.01f;

	[Tooltip("Cached simulation time steps per second in play mode.")]
	[Min(1f)]
	[SerializeField] private float playModeCacheTimeStepsPerSecond = 240f;

	[Tooltip("Coarser cached simulation time steps per second for live edit-mode preview.")]
	[Min(1f)]
	[SerializeField] private float editorPreviewTimeStepsPerSecond = 30f;

	[Tooltip("Detect parameter and control-point changes and rebuild the cache.")]
	[SerializeField] private bool recomputeOnFlightParameterChange = true;

	[SerializeField, HideInInspector]
	private double lookAheadOptimizationDesiredTime = 10.0;

	[Header("Time")]
	[SerializeField] private TimeMode timeMode = TimeMode.AutomaticPreview;
	[SerializeField] private double manualTime;
	[SerializeField] private double playbackSpeed = 1.0;
	[SerializeField] private bool loopPlayback;

	[Header("Position PID")]
	[Tooltip("One independent controller per world axis; all three share these settings.")]
	[SerializeField] private PidSettings positionPid = new PidSettings();
	[Min(0f)] [SerializeField] private float maxMovementSpeed = 12f;
	[Min(0f)] [SerializeField] private float maxAcceleration = 20f;
	[Min(0f)] [SerializeField] private float linearDrag = 0.15f;

	[Header("Aim")]
	[SerializeField] private Transform lookTarget;
	[Range(0f, 1f)] [SerializeField] private float velocityAimInfluence = 0.08f;
	[SerializeField] private Vector3 worldUp = Vector3.up;

	[Header("Rotation Dynamics")]
	[Min(0f)] [SerializeField] private float rotationSpring = 25f;
	[Min(0f)] [SerializeField] private float rotationDamping = 8f;
	[Min(0f)] [SerializeField] private float maxAngularSpeed = 180f;
	[Min(0f)] [SerializeField] private float maxAngularAcceleration = 720f;

	[Header("Velocity Lean")]
	[Tooltip("Forward motion pitches down; backward motion pitches up.")]
	[Range(0f, 60f)]
	[SerializeField] private float maximumForwardPitch = 12f;

	[Range(0f, 60f)]
	[SerializeField] private float maximumBackwardPitch = 8f;

	[Min(0.001f)]
	[SerializeField] private float speedForMaximumPitch = 8f;

	[Range(0f, 30f)]
	[SerializeField] private float accelerationPitchContribution = 3f;

	[Range(0f, 60f)]
	[SerializeField] private float maximumRoll = 20f;

	[Min(0.001f)]
	[SerializeField] private float accelerationForMaximumLean = 12f;

	[Min(0f)]
	[SerializeField] private float leanResponse = 5f;

	[Header("Low-Frequency Imperfection")]
	[Min(0f)] [SerializeField] private float turbulenceAcceleration = 0.35f;
	[Min(0f)] [SerializeField] private float turbulenceFrequency = 0.7f;
	[SerializeField] private Vector3 bodyWobbleDegrees = new Vector3(0.25f, 0.3f, 0.4f);
	[Min(0f)] [SerializeField] private float bodyWobbleFrequency = 8f;

	[Header("Microscopic Motor Shake")]
	[Tooltip("Small local-space positional vibration in meters.")]
	[SerializeField]
	private Vector3 microPositionShake =
		new Vector3(0.0015f, 0.002f, 0.001f);

	[Tooltip("Small high-frequency rotational vibration in degrees.")]
	[SerializeField]
	private Vector3 microRotationShakeDegrees =
		new Vector3(0.045f, 0.055f, 0.07f);

	[Min(0f)]
	[SerializeField] private float microShakeFrequency = 38f;

	[SerializeField] private int noiseSeed = 12345;

	[Header("Gizmos")]
	[SerializeField] private bool drawPointSpline = true;
	[SerializeField] private Color pointSplineColor = new Color(0.15f, 0.8f, 1f, 1f);
	[SerializeField] private Color controlPointColor = new Color(1f, 0.8f, 0.1f, 1f);
	[SerializeField] private Color selectedPointColor = Color.yellow;
	[SerializeField] private bool drawCachedFlightPath = true;
	[SerializeField] private Color cachedFlightPathColor = new Color(1f, 0.25f, 0.1f, 1f);
	[SerializeField] private bool drawCurrentTarget = true;
	[SerializeField] private Color currentTargetColor = Color.magenta;
	[Min(0f)] [SerializeField] private float gizmoPointRadius = 0.12f;

	#endregion

	#region Public State and Cached Data

	public Vector3 Velocity { get; private set; }
	public Vector3 AngularVelocityDegrees { get; private set; }
	public Vector3 CurrentSplineTarget { get; private set; }
	public float DistanceAlongPath { get; private set; }
	public double CurrentTime { get; private set; }
	public int CachedSampleCount => flightCache.Count;
	public double CachedDuration =>
		flightCache.Count > 0 ? flightCache[flightCache.Count - 1].time : 0.0;
	public bool CacheReachedPathEnd { get; private set; }
	public double LastLookAheadOptimizationDuration { get; private set; }
	public double LookAheadOptimizationDesiredTime {
		get => lookAheadOptimizationDesiredTime;
		set => lookAheadOptimizationDesiredTime =
			double.IsNaN(value) || double.IsInfinity(value)
				? 0.001
				: Math.Max(0.001, value);
	}
	public int PathPointCount => pathPoints.Count;
	public int SelectedPathPointIndex => selectedPathPointIndex;
	public Color SelectedPointColor => selectedPointColor;

	private readonly List<Vector3> splineSamples = new List<Vector3>();
	private readonly List<float> splineDistances = new List<float>();
	private readonly List<FlightSample> flightCache = new List<FlightSample>();

	[SerializeField, HideInInspector]
	private List<FlightSample> pregeneratedPlayModeCache =
		new List<FlightSample>();

	[SerializeField, HideInInspector]
	private int pregeneratedPlayModeConfigurationHash;

	[SerializeField, HideInInspector]
	private float pregeneratedPlayModeTimeStepsPerSecond;

	[SerializeField, HideInInspector]
	private bool pregeneratedPlayModeCacheReachedPathEnd;

	private float splineLength;
	private double automaticTime;
	private double lastEditorClock;
	private double lastAppliedTime = double.NaN;
	private int configurationHash;
	private int cacheRevision;
	private int lastAppliedCacheRevision = -1;
	private bool initialized;
	private bool recomputing;
	[NonSerialized] private int selectedPathPointIndex = -1;

	#endregion

	#region Lifecycle and Cache Generation

	private void OnEnable() {
		Initialize();
	}

	public override void Initialize() {
		if (pathPoints == null)
			pathPoints = new List<Vector3>();

		if (positionPid == null)
			positionPid = new PidSettings();

		automaticTime = 0.0;
		lastEditorClock = Time.realtimeSinceStartupAsDouble;
		initialized = true;

		if (!Application.isPlaying || !LoadPregeneratedPlayModeCache())
			Recompute();

		ApplyTime(timeMode == TimeMode.ManualDeterministic ? manualTime : automaticTime, true);
	}

	public void Recompute() {
		double timeStepsPerSecond = Application.isPlaying
			? playModeCacheTimeStepsPerSecond
			: editorPreviewTimeStepsPerSecond;

		Recompute(timeStepsPerSecond);
	}

	public void Recompute(double timeStepsPerSecond) {
		if (recomputing)
			return;

		if (positionPid == null)
			positionPid = new PidSettings();

		recomputing = true;

		try {
			timeStepsPerSecond = Math.Max(1.0, timeStepsPerSecond);
			double timeStep = 1.0 / timeStepsPerSecond;
			RebuildSplineCache();
			flightCache.Clear();
			CacheReachedPathEnd = false;

			if (splineSamples.Count == 0) {
				configurationHash = ComputeConfigurationHash();
				cacheRevision++;
				return;
			}

			bool pathHasTraversal =
				splineSamples.Count >= 2 &&
				splineLength > Mathf.Epsilon;

			Vector3 initialPosition = GetValidPoint(0);
			Quaternion initialRotation = GetIdealPathRotation(initialPosition, 0f);

			SimulationState state = new SimulationState
			{
				position = initialPosition,
				rotation = initialRotation,
				velocity = initialVelocity,
				angularVelocity = Vector3.zero,
				lean = Vector2.zero,
				pathDistance = 0f,
				time = 0.0
			};

			state.splineTarget =
				startupHoverTime > 0f || !pathHasTraversal
					? initialPosition
					: GetPointAtDistance(
						state.pathDistance + lookAheadDistance);
			AddFlightSample(state);

			Vector3 startupHoverDirection =
				GetTangentAtDistance(0f);

			SimulateHoverPhase(
				ref state,
				GetValidPoint(0),
				startupHoverDirection,
				startupHoverTime,
				timeStep);

			if (pathHasTraversal) {
				PidController pathPidX = new PidController(positionPid);
				PidController pathPidY = new PidController(positionPid);
				PidController pathPidZ = new PidController(positionPid);
				double pathStartTime = state.time;

				while (!HasReachedPathEnd(state) &&
					   state.time - pathStartTime <
						   MaximumCacheSimulationSeconds) {
					SimulatePathStep(
						ref state,
						pathPidX,
						pathPidY,
						pathPidZ,
						(float)timeStep);
					AddFlightSample(state);
				}

				CacheReachedPathEnd = HasReachedPathEnd(state);
			} else {
				CacheReachedPathEnd = true;
			}

			if (CacheReachedPathEnd && endingHoverTime > 0f) {
				Vector3 endingAnchor = closedLoop
					? GetValidPoint(0)
					: GetValidPoint(pathPoints.Count - 1);

				Vector3 endingHoverDirection = pathHasTraversal
					? GetTangentAtDistance(splineLength)
					: startupHoverDirection;

				SimulateHoverPhase(
					ref state,
					endingAnchor,
					endingHoverDirection,
					endingHoverTime,
					timeStep);
			}

			configurationHash = ComputeConfigurationHash();
			cacheRevision++;
			lastAppliedCacheRevision = -1;
		} finally {
			recomputing = false;
		}
	}

	public void PregeneratePlayModeCache() {
		Recompute(playModeCacheTimeStepsPerSecond);

		if (pregeneratedPlayModeCache == null)
			pregeneratedPlayModeCache = new List<FlightSample>();

		pregeneratedPlayModeCache.Clear();
		pregeneratedPlayModeCache.AddRange(flightCache);
		pregeneratedPlayModeConfigurationHash =
			ComputeConfigurationHash();
		pregeneratedPlayModeTimeStepsPerSecond =
			playModeCacheTimeStepsPerSecond;
		pregeneratedPlayModeCacheReachedPathEnd =
			CacheReachedPathEnd;

#if UNITY_EDITOR
		EditorUtility.SetDirty(this);
#endif
	}

	public void OptimizeLookAheadDistance(double desiredTimeSeconds) {
		desiredTimeSeconds =
			double.IsNaN(desiredTimeSeconds) ||
			double.IsInfinity(desiredTimeSeconds)
				? 0.001
				: Math.Max(0.001, desiredTimeSeconds);
		lookAheadOptimizationDesiredTime = desiredTimeSeconds;
		RebuildSplineCache();

		if (splineSamples.Count < 2 || splineLength <= Mathf.Epsilon) {
			Debug.LogWarning(
				"Look-ahead optimization requires at least two path points.",
				this);
			return;
		}

		float originalLookAhead = lookAheadDistance;
		float minimumLookAhead = Mathf.Max(0.001f, splineLength * 0.0001f);
		float maximumLookAhead = Mathf.Max(minimumLookAhead * 2f, splineLength);
		float bestLookAhead = Mathf.Clamp(
			lookAheadDistance,
			minimumLookAhead,
			maximumLookAhead);

		double previewRate = Math.Max(
			1.0,
			editorPreviewTimeStepsPerSecond);

		double bestDuration;
		double bestError = EvaluateLookAheadCandidate(
			bestLookAhead,
			desiredTimeSeconds,
			previewRate,
			out bestDuration);

		const int coarseTrialCount = 12;
		double logarithmicRange = Math.Log(
			maximumLookAhead / minimumLookAhead);
		double localRatio = Math.Exp(
			logarithmicRange / (coarseTrialCount - 1));

		for (int i = 0; i < coarseTrialCount; i++) {
			float candidate = minimumLookAhead * (float)Math.Exp(
				logarithmicRange * i / (coarseTrialCount - 1));

			double duration;
			double error = EvaluateLookAheadCandidate(
				candidate,
				desiredTimeSeconds,
				previewRate,
				out duration);

			if (error >= bestError)
				continue;

			bestError = error;
			bestDuration = duration;
			bestLookAhead = candidate;
		}

		if (double.IsPositiveInfinity(bestError)) {
			lookAheadDistance = originalLookAhead;
			Recompute();
			Debug.LogWarning(
				"No look-ahead distance completed the path with the current flight settings.",
				this);
			return;
		}

		float lower = Mathf.Max(
			minimumLookAhead,
			bestLookAhead / (float)localRatio);
		float upper = Mathf.Min(
			maximumLookAhead,
			bestLookAhead * (float)localRatio);

		const float inverseGoldenRatio = 0.61803398875f;
		float c = upper - (upper - lower) * inverseGoldenRatio;
		float d = lower + (upper - lower) * inverseGoldenRatio;

		double cDuration;
		double cError = EvaluateLookAheadCandidate(
			c,
			desiredTimeSeconds,
			previewRate,
			out cDuration);

		double dDuration;
		double dError = EvaluateLookAheadCandidate(
			d,
			desiredTimeSeconds,
			previewRate,
			out dDuration);

		for (int i = 0; i < 8; i++) {
			if (cError <= dError) {
				upper = d;
				d = c;
				dError = cError;
				dDuration = cDuration;
				c = upper - (upper - lower) * inverseGoldenRatio;
				cError = EvaluateLookAheadCandidate(
					c,
					desiredTimeSeconds,
					previewRate,
					out cDuration);
			} else {
				lower = c;
				c = d;
				cError = dError;
				cDuration = dDuration;
				d = lower + (upper - lower) * inverseGoldenRatio;
				dError = EvaluateLookAheadCandidate(
					d,
					desiredTimeSeconds,
					previewRate,
					out dDuration);
			}
		}

		if (cError < bestError) {
			bestError = cError;
			bestDuration = cDuration;
			bestLookAhead = c;
		}

		if (dError < bestError) {
			bestError = dError;
			bestDuration = dDuration;
			bestLookAhead = d;
		}

		double playModeRate = Math.Max(
			1.0,
			playModeCacheTimeStepsPerSecond);

		bestError = EvaluateLookAheadCandidate(
			bestLookAhead,
			desiredTimeSeconds,
			playModeRate,
			out bestDuration);

		float refinementStep = Mathf.Max(
			(upper - lower) * 0.25f,
			maximumLookAhead * 0.0025f);

		for (int i = 0; i < 5; i++) {
			float center = bestLookAhead;
			float left = Mathf.Max(
				minimumLookAhead,
				center - refinementStep);
			float right = Mathf.Min(
				maximumLookAhead,
				center + refinementStep);

			double leftDuration;
			double leftError = EvaluateLookAheadCandidate(
				left,
				desiredTimeSeconds,
				playModeRate,
				out leftDuration);

			if (leftError < bestError) {
				bestError = leftError;
				bestDuration = leftDuration;
				bestLookAhead = left;
			}

			double rightDuration;
			double rightError = EvaluateLookAheadCandidate(
				right,
				desiredTimeSeconds,
				playModeRate,
				out rightDuration);

			if (rightError < bestError) {
				bestError = rightError;
				bestDuration = rightDuration;
				bestLookAhead = right;
			}

			refinementStep *= 0.5f;
		}

		lookAheadDistance = bestLookAhead;
		Recompute(playModeRate);
		LastLookAheadOptimizationDuration = CachedDuration;

		if (!Application.isPlaying && selectedPathPointIndex >= 0) {
			ApplySelectedPointPreview();
		} else {
			double requestedTime =
				timeMode == TimeMode.ManualDeterministic
					? manualTime
					: automaticTime;
			ApplyTime(requestedTime, true);
		}
	}

	private double EvaluateLookAheadCandidate(
		float candidate,
		double desiredTimeSeconds,
		double timeStepsPerSecond,
		out double duration) {
		lookAheadDistance = candidate;
		Recompute(timeStepsPerSecond);
		duration = CachedDuration;

		return CacheReachedPathEnd
			? Math.Abs(duration - desiredTimeSeconds)
			: double.PositiveInfinity;
	}

	private bool LoadPregeneratedPlayModeCache() {
		if (pregeneratedPlayModeCache == null ||
			pregeneratedPlayModeCache.Count == 0 ||
			pregeneratedPlayModeConfigurationHash !=
				ComputeConfigurationHash() ||
			!Mathf.Approximately(
				pregeneratedPlayModeTimeStepsPerSecond,
				playModeCacheTimeStepsPerSecond)) {
			return false;
		}

		RebuildSplineCache();
		flightCache.Clear();
		flightCache.AddRange(pregeneratedPlayModeCache);
		configurationHash = pregeneratedPlayModeConfigurationHash;
		CacheReachedPathEnd =
			pregeneratedPlayModeCacheReachedPathEnd;
		cacheRevision++;
		lastAppliedCacheRevision = -1;
		return true;
	}

	#endregion

	#region Path Editing and Playback Control

	public void SetManualTime(double time) {
		timeMode = TimeMode.ManualDeterministic;
		manualTime = time;

		if (recomputeOnFlightParameterChange &&
			ComputeConfigurationHash() != configurationHash) {
			Recompute();
		}

		ApplyTime(manualTime, true);
	}

	public Vector3 GetPathPoint(int index) {
		return pathPoints[index];
	}

	public void SetPathPoint(int index, Vector3 worldPosition) {
		if (index < 0 || index >= pathPoints.Count)
			return;

		pathPoints[index] = worldPosition;
		Recompute();

		if (!Application.isPlaying && selectedPathPointIndex == index)
			ApplySelectedPointPreview();
	}

	public void SelectPathPointForPreview(int index) {
		selectedPathPointIndex =
			index >= 0 && index < pathPoints.Count ? index : -1;

		if (!Application.isPlaying && selectedPathPointIndex >= 0)
			ApplySelectedPointPreview();
	}

	public void ClearPathPointSelection() {
		selectedPathPointIndex = -1;
		lastAppliedCacheRevision = -1;
	}

	public override void UpdateMotion(ulong t) {
		ApplyTime(t / (double)DVConfig.timeScale, false);
	}

	private void Update() {
		if (timeMode == TimeMode.AutomaticPreview) {
			if (!initialized)
				Initialize();

			EnsureCacheIsCurrent();

			if (flightCache.Count == 0)
				return;

			if (!Application.isPlaying && selectedPathPointIndex >= 0) {
				ApplySelectedPointPreview();
				return;
			}

			if (Application.isPlaying) {
				automaticTime += Time.deltaTime * playbackSpeed;
				ApplyTime(automaticTime, false);
			} else {
				ApplyTime(manualTime, false);
			}
		}
	}

	private void EnsureCacheIsCurrent() {
		if (recomputeOnFlightParameterChange &&
			!recomputing &&
			ComputeConfigurationHash() != configurationHash) {
			Recompute();
		}
	}

#endregion

	#region Flight Simulation

	// Advances one path-following simulation step and updates closest-path progress.
	private void SimulatePathStep(
		ref SimulationState state,
		PidController pidX,
		PidController pidY,
		PidController pidZ,
		float dt) {
		UpdateClosestPathDistance(ref state);
		state.splineTarget = GetPointAtDistance(state.pathDistance + lookAheadDistance);

		Vector3 measuredAcceleration = SimulatePositionTowards(
			ref state,
			state.splineTarget,
			pidX,
			pidY,
			pidZ,
			dt);

		UpdateClosestPathDistance(ref state);
		state.splineTarget = GetPointAtDistance(state.pathDistance + lookAheadDistance);

		Vector3 pathDirection =
			GetTangentAtDistance(state.pathDistance + lookAheadDistance);

		UpdateRotation(
			ref state,
			measuredAcceleration,
			pathDirection,
			dt);
		state.time += dt;
	}

	// Simulates a timed hover around a fixed anchor without advancing path progress.
	private void SimulateHoverPhase(
		ref SimulationState state,
		Vector3 hoverAnchor,
		Vector3 hoverDirection,
		double duration,
		double timeStep) {
		if (duration <= 0.0)
			return;

		PidController hoverPidX = new PidController(positionPid);
		PidController hoverPidY = new PidController(positionPid);
		PidController hoverPidZ = new PidController(positionPid);
		double endTime = state.time + duration;

		while (state.time < endTime) {
			float dt = (float)Math.Min(
				timeStep,
				endTime - state.time);

			if (dt <= 0f)
				break;

			SimulateHoverStep(
				ref state,
				hoverAnchor,
				hoverDirection,
				hoverPidX,
				hoverPidY,
				hoverPidZ,
				dt);
			AddFlightSample(state);
		}
	}

	// Advances one hover step while keeping the position controller centered on its anchor.
	private void SimulateHoverStep(
		ref SimulationState state,
		Vector3 hoverAnchor,
		Vector3 hoverDirection,
		PidController pidX,
		PidController pidY,
		PidController pidZ,
		float dt) {
		state.splineTarget = hoverAnchor;
		Vector3 measuredAcceleration = SimulatePositionTowards(
			ref state,
			hoverAnchor,
			pidX,
			pidY,
			pidZ,
			dt);

		UpdateRotation(
			ref state,
			measuredAcceleration,
			hoverDirection,
			dt);
		state.time += dt;
	}

	// Applies PID acceleration, turbulence, drag, and speed limiting toward a target.
	private Vector3 SimulatePositionTowards(
		ref SimulationState state,
		Vector3 positionTarget,
		PidController pidX,
		PidController pidY,
		PidController pidZ,
		float dt) {
		Vector3 error = positionTarget - state.position;
		Vector3 pidAcceleration = new Vector3(
			pidX.Update(error.x, dt),
			pidY.Update(error.y, dt),
			pidZ.Update(error.z, dt));

		Vector3 turbulence = SampleNoiseVector(
			state.time * turbulenceFrequency,
			11.37f) * turbulenceAcceleration;

		Vector3 commandedAcceleration = Vector3.ClampMagnitude(
			pidAcceleration + turbulence,
			maxAcceleration);

		Vector3 previousVelocity = state.velocity;
		state.velocity += commandedAcceleration * dt;
		state.velocity *= Mathf.Exp(-linearDrag * dt);
		state.velocity = Vector3.ClampMagnitude(state.velocity, maxMovementSpeed);
		state.position += state.velocity * dt;

		return (state.velocity - previousVelocity) / dt;
	}

	private void UpdateClosestPathDistance(ref SimulationState state) {
		float closestDistance = FindClosestDistance(state.position);

		if (!closedLoop) {
			state.pathDistance = preventBackwardProgress
				? Mathf.Max(state.pathDistance, closestDistance)
				: closestDistance;
			return;
		}

		float previousWrappedDistance = Mathf.Repeat(state.pathDistance, splineLength);
		float delta = closestDistance - previousWrappedDistance;
		float halfLength = splineLength * 0.5f;

		if (delta < -halfLength)
			delta += splineLength;
		else if (delta > halfLength)
			delta -= splineLength;

		if (preventBackwardProgress)
			delta = Mathf.Max(0f, delta);

		state.pathDistance = Mathf.Max(0f, state.pathDistance + delta);
	}

	private bool HasReachedPathEnd(SimulationState state) {
		if (!closedLoop)
			return state.pathDistance >= splineLength - pathCompletionTolerance;

		return state.pathDistance >= splineLength;
	}

	private Quaternion GetIdealPathRotation(Vector3 position, float pathDistance) {
		Vector3 forward = lookTarget
			? lookTarget.position - position
			: GetTangentAtDistance(pathDistance);

		if (forward.sqrMagnitude < 0.000001f)
			forward = Vector3.forward;

		Vector3 up = worldUp.sqrMagnitude > 0.000001f
			? worldUp.normalized
			: Vector3.up;

		if (Mathf.Abs(Vector3.Dot(forward.normalized, up)) > 0.999f)
			up = Vector3.forward;

		return Quaternion.LookRotation(forward.normalized, up);
	}

	// Integrates angular velocity toward the target-facing, velocity-leaned orientation.
	private void UpdateRotation(
		ref SimulationState state,
		Vector3 acceleration,
		Vector3 pathDirection,
		float dt) {
		Vector3 aimDirection = lookTarget
			? lookTarget.position - state.position
			: pathDirection;

		if (aimDirection.sqrMagnitude < 0.000001f)
			aimDirection = state.rotation * Vector3.forward;

		Vector3 velocityDirection = state.velocity.sqrMagnitude > 0.0001f
			? state.velocity.normalized
			: pathDirection;

		if (velocityDirection.sqrMagnitude > 0.000001f) {
			aimDirection = Vector3.Slerp(
				aimDirection.normalized,
				velocityDirection.normalized,
				velocityAimInfluence);
		}

		Vector3 up = worldUp.sqrMagnitude > 0.000001f
			? worldUp.normalized
			: Vector3.up;

		if (Mathf.Abs(Vector3.Dot(aimDirection.normalized, up)) > 0.999f)
			up = state.rotation * Vector3.up;

		Quaternion aimRotation = Quaternion.LookRotation(aimDirection.normalized, up);
		Vector3 localVelocity = Quaternion.Inverse(aimRotation) * state.velocity;
		Vector3 localAcceleration = Quaternion.Inverse(aimRotation) * acceleration;

		float forwardRatio = Mathf.Clamp(
			localVelocity.z / speedForMaximumPitch,
			-1f,
			1f);

		float velocityPitch = forwardRatio >= 0f
			? forwardRatio * maximumForwardPitch
			: forwardRatio * maximumBackwardPitch;

		float accelerationPitch =
			Mathf.Clamp(
				localAcceleration.z / accelerationForMaximumLean,
				-1f,
				1f) *
			accelerationPitchContribution;

		float desiredPitch = Mathf.Clamp(
			velocityPitch + accelerationPitch,
			-maximumBackwardPitch,
			maximumForwardPitch);

		if (localVelocity.z > 0.0001f)
			desiredPitch = Mathf.Max(0f, desiredPitch);
		else if (localVelocity.z < -0.0001f)
			desiredPitch = Mathf.Min(0f, desiredPitch);

		float desiredRoll =
			Mathf.Clamp(
				-localAcceleration.x / accelerationForMaximumLean,
				-1f,
				1f) *
			maximumRoll;

		float leanBlend = 1f - Mathf.Exp(-leanResponse * dt);
		state.lean = Vector2.Lerp(
			state.lean,
			new Vector2(desiredPitch, desiredRoll),
			leanBlend);

		Vector3 wobble = Vector3.Scale(
			SampleNoiseVector(state.time * bodyWobbleFrequency, 83.91f),
			bodyWobbleDegrees);

		Quaternion desiredRotation =
			aimRotation *
			Quaternion.Euler(state.lean.x, 0f, state.lean.y) *
			Quaternion.Euler(wobble);

		Quaternion rotationError =
			desiredRotation * Quaternion.Inverse(state.rotation);

		rotationError.ToAngleAxis(out float errorDegrees, out Vector3 errorAxis);
		if (errorDegrees > 180f)
			errorDegrees -= 360f;

		Vector3 angularAcceleration =
			-rotationDamping * state.angularVelocity;

		if (errorAxis.sqrMagnitude > 0.000001f && !float.IsNaN(errorAxis.x)) {
			angularAcceleration +=
				errorAxis.normalized *
				(errorDegrees * Mathf.Deg2Rad * rotationSpring);
		}

		angularAcceleration = Vector3.ClampMagnitude(
			angularAcceleration,
			maxAngularAcceleration * Mathf.Deg2Rad);

		state.angularVelocity += angularAcceleration * dt;
		state.angularVelocity = Vector3.ClampMagnitude(
			state.angularVelocity,
			maxAngularSpeed * Mathf.Deg2Rad);

		float angularStep = state.angularVelocity.magnitude * dt;
		if (angularStep > 0.000001f) {
			state.rotation =
				Quaternion.AngleAxis(
					angularStep * Mathf.Rad2Deg,
					state.angularVelocity.normalized) *
				state.rotation;
		}
	}

	// Produces a deterministic three-axis Perlin disturbance for the configured seed.
	private Vector3 SampleNoiseVector(double time, float offset) {
		float t = (float)time;
		float seed = noiseSeed * 0.00137f + offset;

		return new Vector3(
			Mathf.PerlinNoise(seed + 13.1f, t) * 2f - 1f,
			Mathf.PerlinNoise(seed + 37.7f, t + 19.4f) * 2f - 1f,
			Mathf.PerlinNoise(seed + 71.3f, t + 43.8f) * 2f - 1f);
	}

	// Stores the physical pose plus deterministic high-frequency motor vibration.
	private void AddFlightSample(SimulationState state) {
		Vector3 micro = Vector3.zero;
		if (state.time > double.Epsilon) {
			Vector3 microA = SampleNoiseVector(
				state.time * microShakeFrequency,
				127.31f);

			Vector3 microB = SampleNoiseVector(
				state.time * microShakeFrequency * 1.913,
				211.73f);

			micro = microA * 0.65f + microB * 0.35f;
		}

		Vector3 positionOffset =
			state.rotation * Vector3.Scale(micro, microPositionShake);

		Quaternion rotationOffset = Quaternion.Euler(
			Vector3.Scale(micro, microRotationShakeDegrees));

		flightCache.Add(new FlightSample {
			time = state.time,
			position = state.position + positionOffset,
			rotation = state.rotation * rotationOffset,
			velocity = state.velocity,
			splineTarget = state.splineTarget,
			pathDistance = state.pathDistance
		});
	}

	#endregion

	#region Cached Pose Sampling

	private void ApplyTime(double requestedTime, bool force) {
		if (flightCache.Count == 0)
			return;

		double time = ResolvePlaybackTime(requestedTime);
		if (!force &&
			lastAppliedCacheRevision == cacheRevision &&
			time.Equals(lastAppliedTime)) {
			return;
		}

		int upper = FindUpperSampleIndex(time);
		int lower = Math.Max(0, upper - 1);
		FlightSample a = flightCache[lower];
		FlightSample b = flightCache[upper];

		double interval = b.time - a.time;
		float blend = interval > double.Epsilon
			? (float)((time - a.time) / interval)
			: 0f;

		transform.SetPositionAndRotation(
			Vector3.LerpUnclamped(a.position, b.position, blend),
			Quaternion.SlerpUnclamped(a.rotation, b.rotation, blend));

		Velocity = Vector3.LerpUnclamped(a.velocity, b.velocity, blend);
		CurrentSplineTarget = Vector3.LerpUnclamped(
			a.splineTarget,
			b.splineTarget,
			blend);
		DistanceAlongPath = Mathf.LerpUnclamped(
			a.pathDistance,
			b.pathDistance,
			blend);

		if (interval > double.Epsilon) {
			Quaternion delta = b.rotation * Quaternion.Inverse(a.rotation);
			delta.ToAngleAxis(out float degrees, out Vector3 axis);
			if (degrees > 180f)
				degrees -= 360f;

			AngularVelocityDegrees = axis.sqrMagnitude > 0.000001f
				? axis.normalized * (degrees / (float)interval)
				: Vector3.zero;
		} else {
			AngularVelocityDegrees = Vector3.zero;
		}

		CurrentTime = time;
		lastAppliedTime = time;
		lastAppliedCacheRevision = cacheRevision;
	}

	private void ApplySelectedPointPreview() {
		if (selectedPathPointIndex < 0 ||
			selectedPathPointIndex >= pathPoints.Count) {
			selectedPathPointIndex = -1;
			return;
		}

		Vector3 previewPosition = pathPoints[selectedPathPointIndex];
		float controlPointDistance =
			GetControlPointPathDistance(selectedPathPointIndex);

		Quaternion previewRotation =
			GetIdealPathRotation(previewPosition, controlPointDistance);
		FlightSample closestSample = default;
		bool hasSample = false;
		float bestDistance = float.PositiveInfinity;

		for (int i = 0; i < flightCache.Count; i++) {
			float distance = Mathf.Abs(
				flightCache[i].pathDistance - controlPointDistance);

			if (distance >= bestDistance)
				continue;

			bestDistance = distance;
			closestSample = flightCache[i];
			hasSample = true;
		}

		if (hasSample) {
			previewRotation = closestSample.rotation;
			Velocity = closestSample.velocity;
			CurrentTime = closestSample.time;
		} else {
			Velocity = Vector3.zero;
			CurrentTime = 0.0;
		}

		transform.SetPositionAndRotation(previewPosition, previewRotation);
		DistanceAlongPath = controlPointDistance;
		CurrentSplineTarget =
			GetPointAtDistance(controlPointDistance + lookAheadDistance);
		AngularVelocityDegrees = Vector3.zero;
	}

	private float GetControlPointPathDistance(int pointIndex) {
		if (splineDistances.Count == 0)
			return 0f;

		int sampleIndex = Mathf.Clamp(
			pointIndex * Mathf.Max(4, splineSamplesPerSegment),
			0,
			splineDistances.Count - 1);

		return splineDistances[sampleIndex];
	}

	private double ResolvePlaybackTime(double time) {
		if (double.IsNaN(time) || double.IsInfinity(time))
			return 0.0;

		double duration = flightCache[flightCache.Count - 1].time;
		if (duration <= 0.0)
			return 0.0;

		if (loopPlayback) {
			time %= duration;
			if (time < 0.0)
				time += duration;
			return time;
		}

		return Math.Max(0.0, Math.Min(duration, time));
	}

	private int FindUpperSampleIndex(double time) {
		int low = 0;
		int high = flightCache.Count - 1;

		while (low < high) {
			int mid = (low + high) / 2;
			if (flightCache[mid].time < time)
				low = mid + 1;
			else
				high = mid;
		}

		return low;
	}

	#endregion

	#region Spline Sampling

	private void RebuildSplineCache() {
		splineSamples.Clear();
		splineDistances.Clear();
		splineLength = 0f;

		int pointCount = pathPoints.Count;
		if (pointCount == 0)
			return;

		if (pointCount == 1) {
			splineSamples.Add(GetValidPoint(0));
			splineDistances.Add(0f);
			return;
		}

		int segmentCount = closedLoop ? pointCount : pointCount - 1;
		int resolution = Mathf.Max(4, splineSamplesPerSegment);
		Vector3 previous = Vector3.zero;
		bool hasPrevious = false;

		for (int segment = 0; segment < segmentCount; segment++) {
			for (int sample = 0; sample < resolution; sample++) {
				float t = sample / (float)resolution;
				AddSplineSample(
					EvaluateSplineSegment(segment, t),
					ref previous,
					ref hasPrevious);
			}
		}

		AddSplineSample(
			EvaluateSplineSegment(segmentCount - 1, 1f),
			ref previous,
			ref hasPrevious);
	}

	private void AddSplineSample(
		Vector3 point,
		ref Vector3 previous,
		ref bool hasPrevious) {
		if (hasPrevious)
			splineLength += Vector3.Distance(previous, point);

		splineSamples.Add(point);
		splineDistances.Add(splineLength);
		previous = point;
		hasPrevious = true;
	}

	private Vector3 EvaluateSplineSegment(int segment, float t) {
		int count = pathPoints.Count;
		int i0 = closedLoop ? HF.WrapIndex(segment - 1, count) : Mathf.Max(segment - 1, 0);
		int i1 = closedLoop ? HF.WrapIndex(segment, count) : segment;
		int i2 = closedLoop ? HF.WrapIndex(segment + 1, count) : Mathf.Min(segment + 1, count - 1);
		int i3 = closedLoop ? HF.WrapIndex(segment + 2, count) : Mathf.Min(segment + 2, count - 1);

		Vector3 p0 = GetValidPoint(i0);
		Vector3 p1 = GetValidPoint(i1);
		Vector3 p2 = GetValidPoint(i2);
		Vector3 p3 = GetValidPoint(i3);

		float t2 = t * t;
		float t3 = t2 * t;

		return 0.5f * (
			2f * p1 +
			(-p0 + p2) * t +
			(2f * p0 - 5f * p1 + 4f * p2 - p3) * t2 +
			(-p0 + 3f * p1 - 3f * p2 + p3) * t3);
	}

	private float FindClosestDistance(Vector3 point) {
		if (splineSamples.Count < 2)
			return 0f;

		float bestSquaredDistance = float.PositiveInfinity;
		float bestPathDistance = 0f;

		for (int i = 0; i < splineSamples.Count - 1; i++) {
			Vector3 a = splineSamples[i];
			Vector3 segment = splineSamples[i + 1] - a;
			float squaredLength = segment.sqrMagnitude;
			float t = squaredLength > 0.000001f
				? Mathf.Clamp01(Vector3.Dot(point - a, segment) / squaredLength)
				: 0f;

			float squaredDistance = (point - (a + segment * t)).sqrMagnitude;
			if (squaredDistance >= bestSquaredDistance)
				continue;

			bestSquaredDistance = squaredDistance;
			bestPathDistance = Mathf.Lerp(
				splineDistances[i],
				splineDistances[i + 1],
				t);
		}

		return bestPathDistance;
	}

	private Vector3 GetPointAtDistance(float distance) {
		if (splineSamples.Count == 0)
			return transform.position;

		if (splineLength <= Mathf.Epsilon)
			return splineSamples[0];

		distance = closedLoop
			? Mathf.Repeat(distance, splineLength)
			: Mathf.Clamp(distance, 0f, splineLength);

		int upper = FindUpperSplineDistanceIndex(distance);
		int lower = Mathf.Max(0, upper - 1);
		float interval = splineDistances[upper] - splineDistances[lower];
		float blend = interval > Mathf.Epsilon
			? (distance - splineDistances[lower]) / interval
			: 0f;

		return Vector3.LerpUnclamped(
			splineSamples[lower],
			splineSamples[upper],
			blend);
	}

	private Vector3 GetTangentAtDistance(float distance) {
		if (splineSamples.Count < 2)
			return Vector3.forward;

		float probe = Mathf.Max(
			0.02f,
			splineLength / Mathf.Max(2, splineSamples.Count - 1));

		Vector3 tangent =
			GetPointAtDistance(distance + probe) -
			GetPointAtDistance(distance - probe);

		if (tangent.sqrMagnitude < 0.000001f) {
			tangent =
				GetPointAtDistance(distance + probe) -
				GetPointAtDistance(distance);
		}

		return tangent.sqrMagnitude > 0.000001f
			? tangent.normalized
			: Vector3.forward;
	}

	private int FindUpperSplineDistanceIndex(float distance) {
		int low = 0;
		int high = splineDistances.Count - 1;

		while (low < high) {
			int mid = (low + high) / 2;
			if (splineDistances[mid] < distance)
				low = mid + 1;
			else
				high = mid;
		}

		return low;
	}

	private Vector3 GetValidPoint(int validIndex) {
		return validIndex >= 0 && validIndex < pathPoints.Count
			? pathPoints[validIndex]
			: transform.position;
	}

	#endregion

	#region Configuration Validation and Gizmos

	private int ComputeConfigurationHash() {
		unchecked {
			int hash = 17;

			HF.CombineHash(ref hash, closedLoop);
			HF.CombineHash(ref hash, lookAheadDistance);
			HF.CombineHash(ref hash, splineSamplesPerSegment);
			HF.CombineHash(ref hash, preventBackwardProgress);
			HF.CombineHash(ref hash, startupHoverTime);
			HF.CombineHash(ref hash, endingHoverTime);
			HF.CombineHash(ref hash, pathCompletionTolerance);
			HF.CombineHash(ref hash, playModeCacheTimeStepsPerSecond);
			HF.CombineHash(ref hash, editorPreviewTimeStepsPerSecond);

			for (int i = 0; i < pathPoints.Count; i++)
				HF.CombineHash(ref hash, pathPoints[i]);

			HF.CombineHash(ref hash, initialVelocity);
			HF.CombineHash(ref hash, positionPid.proportional);
			HF.CombineHash(ref hash, positionPid.integral);
			HF.CombineHash(ref hash, positionPid.derivative);
			HF.CombineHash(ref hash, positionPid.integralLimit);
			HF.CombineHash(ref hash, positionPid.derivativeResponse);
			HF.CombineHash(ref hash, maxMovementSpeed);
			HF.CombineHash(ref hash, maxAcceleration);
			HF.CombineHash(ref hash, linearDrag);

			HF.CombineHash(ref hash, lookTarget ? lookTarget.GetInstanceID() : 0);
			if (lookTarget && lookTarget != transform)
				HF.CombineHash(ref hash, lookTarget.position);

			HF.CombineHash(ref hash, velocityAimInfluence);
			HF.CombineHash(ref hash, worldUp);
			HF.CombineHash(ref hash, rotationSpring);
			HF.CombineHash(ref hash, rotationDamping);
			HF.CombineHash(ref hash, maxAngularSpeed);
			HF.CombineHash(ref hash, maxAngularAcceleration);
			HF.CombineHash(ref hash, maximumForwardPitch);
			HF.CombineHash(ref hash, maximumBackwardPitch);
			HF.CombineHash(ref hash, speedForMaximumPitch);
			HF.CombineHash(ref hash, accelerationPitchContribution);
			HF.CombineHash(ref hash, maximumRoll);
			HF.CombineHash(ref hash, accelerationForMaximumLean);
			HF.CombineHash(ref hash, leanResponse);
			HF.CombineHash(ref hash, turbulenceAcceleration);
			HF.CombineHash(ref hash, turbulenceFrequency);
			HF.CombineHash(ref hash, bodyWobbleDegrees);
			HF.CombineHash(ref hash, bodyWobbleFrequency);
			HF.CombineHash(ref hash, microPositionShake);
			HF.CombineHash(ref hash, microRotationShakeDegrees);
			HF.CombineHash(ref hash, microShakeFrequency);
			HF.CombineHash(ref hash, noiseSeed);

			return hash;
		}
	}

	private void OnValidate() {
		if (pathPoints == null)
			pathPoints = new List<Vector3>();

		if (pregeneratedPlayModeCache == null)
			pregeneratedPlayModeCache = new List<FlightSample>();

		if (selectedPathPointIndex >= pathPoints.Count)
			selectedPathPointIndex = -1;

		splineSamplesPerSegment = Mathf.Max(4, splineSamplesPerSegment);
		startupHoverTime = Mathf.Max(0f, startupHoverTime);
		endingHoverTime = Mathf.Max(0f, endingHoverTime);
		pathCompletionTolerance = Mathf.Max(0.0001f, pathCompletionTolerance);
		playModeCacheTimeStepsPerSecond = Mathf.Max(1f, playModeCacheTimeStepsPerSecond);
		editorPreviewTimeStepsPerSecond = Mathf.Max(1f, editorPreviewTimeStepsPerSecond);
		speedForMaximumPitch = Mathf.Max(0.001f, speedForMaximumPitch);
		accelerationForMaximumLean = Mathf.Max(0.001f, accelerationForMaximumLean);

		if (positionPid == null)
			positionPid = new PidSettings();
	}

	private void OnDrawGizmos() {
		EnsureCacheIsCurrent();

		if (drawPointSpline && pathPoints.Count > 0) {
			Gizmos.color = pointSplineColor;
			for (int i = 1; i < splineSamples.Count; i++)
				Gizmos.DrawLine(splineSamples[i - 1], splineSamples[i]);

			Gizmos.color = controlPointColor;
			for (int i = 0; i < pathPoints.Count; i++)
				Gizmos.DrawSphere(pathPoints[i], gizmoPointRadius);

			if (selectedPathPointIndex >= 0 &&
				selectedPathPointIndex < pathPoints.Count) {
				Gizmos.color = selectedPointColor;
				Gizmos.DrawSphere(
					pathPoints[selectedPathPointIndex],
					gizmoPointRadius * 1.6f);
			}
		}

		if (drawCachedFlightPath && flightCache.Count > 1) {
			Gizmos.color = cachedFlightPathColor;
			for (int i = 1; i < flightCache.Count; i++) {
				Gizmos.DrawLine(
					flightCache[i - 1].position,
					flightCache[i].position);
			}
		}

		if (drawCurrentTarget && flightCache.Count > 0) {
			Gizmos.color = currentTargetColor;
			Gizmos.DrawSphere(CurrentSplineTarget, gizmoPointRadius * 1.25f);
			Gizmos.DrawLine(transform.position, CurrentSplineTarget);
		}
	}

	#endregion
}

#if UNITY_EDITOR
[CustomEditor(typeof(DVM_DroneCamera))]
public sealed class DroneCameraMotionEmulatorEditor : Editor {
	private DVM_DroneCamera Drone =>
		(DVM_DroneCamera)target;

	public override void OnInspectorGUI() {
		DrawDefaultInspector();

		using (new EditorGUI.DisabledScope(Application.isPlaying)) {
			EditorGUILayout.BeginHorizontal();
			EditorGUILayout.LabelField(
				"Desired Time (s)",
				GUILayout.Width(105f));

			EditorGUI.BeginChangeCheck();
			double desiredTime = EditorGUILayout.DoubleField(
				Drone.LookAheadOptimizationDesiredTime);
			bool optimizePressed = GUILayout.Button(
				"Optimize Look Ahead",
				GUILayout.Width(145f));

			if (EditorGUI.EndChangeCheck()) {
				Undo.RecordObject(
					Drone,
					"Change Desired Drone Flight Time");
				Drone.LookAheadOptimizationDesiredTime =
					desiredTime;
				EditorUtility.SetDirty(Drone);
			}

			EditorGUILayout.EndHorizontal();

			if (optimizePressed) {
				Undo.RecordObject(
					Drone,
					"Optimize Drone Look Ahead Distance");
				Drone.OptimizeLookAheadDistance(desiredTime);
				EditorUtility.SetDirty(Drone);
				EditorApplication.QueuePlayerLoopUpdate();
				SceneView.RepaintAll();
			}

			if (GUILayout.Button("Pregenerate Play Mode Cache")) {
				Drone.PregeneratePlayModeCache();
				EditorApplication.QueuePlayerLoopUpdate();
				SceneView.RepaintAll();
			}
		}

		if (Drone.SelectedPathPointIndex >= 0 &&
			GUILayout.Button("Clear Path Point Selection")) {
			Drone.ClearPathPointSelection();
			SceneView.RepaintAll();
		}
	}

	private void OnDisable() {
		if (target)
			Drone.ClearPathPointSelection();
	}
}

[InitializeOnLoad]
internal static class DroneCameraMotionEmulatorSceneHandles {
	private const float PointHitRadiusPixels = 14f;

	static DroneCameraMotionEmulatorSceneHandles() {
		SceneView.duringSceneGui += DuringSceneGui;
	}

	private static void DuringSceneGui(SceneView sceneView) {
		if (Application.isPlaying || sceneView.camera == null)
			return;

		UnityEngine.Event currentEvent = UnityEngine.Event.current;
		DVM_DroneCamera activeDrone =
			Selection.activeGameObject
				? Selection.activeGameObject.GetComponent<DVM_DroneCamera>()
				: null;

		if (currentEvent.type == EventType.KeyDown &&
			currentEvent.keyCode == KeyCode.Escape &&
			activeDrone &&
			activeDrone.SelectedPathPointIndex >= 0) {
			activeDrone.ClearPathPointSelection();
			currentEvent.Use();
			SceneView.RepaintAll();
			return;
		}

		DrawSelectedPositionHandle(activeDrone);

		DVM_DroneCamera[] drones =
			UnityEngine.Object.FindObjectsOfType<DVM_DroneCamera>();

		DVM_DroneCamera clickedDrone = null;
		int clickedPointIndex = -1;
		float nearestMouseDistance = PointHitRadiusPixels;
		bool canSelectPoint =
			currentEvent.type == EventType.MouseDown &&
			currentEvent.button == 0 &&
			!currentEvent.alt &&
			GUIUtility.hotControl == 0;

		for (int droneIndex = 0; droneIndex < drones.Length; droneIndex++) {
			DVM_DroneCamera drone = drones[droneIndex];

			for (int pointIndex = 0;
				 pointIndex < drone.PathPointCount;
				 pointIndex++) {
				Vector3 point = drone.GetPathPoint(pointIndex);
				Vector3 viewportPoint =
					sceneView.camera.WorldToViewportPoint(point);

				if (viewportPoint.z <= 0f)
					continue;

				bool selected =
					drone == activeDrone &&
					pointIndex == drone.SelectedPathPointIndex;

				float handleSize =
					HandleUtility.GetHandleSize(point) *
					(selected ? 0.105f : 0.075f);

				Handles.color = selected
					? drone.SelectedPointColor
					: Color.white;

				if (currentEvent.type == EventType.Repaint) {
					Handles.SphereHandleCap(
						0,
						point,
						Quaternion.identity,
						handleSize,
						EventType.Repaint);
				}

				if (!canSelectPoint || selected)
					continue;

				float mouseDistance = Vector2.Distance(
					currentEvent.mousePosition,
					HandleUtility.WorldToGUIPoint(point));

				if (mouseDistance > nearestMouseDistance)
					continue;

				nearestMouseDistance = mouseDistance;
				clickedDrone = drone;
				clickedPointIndex = pointIndex;
			}
		}

		if (!clickedDrone)
			return;

		Selection.activeGameObject = clickedDrone.gameObject;
		clickedDrone.SelectPathPointForPreview(clickedPointIndex);
		EditorApplication.QueuePlayerLoopUpdate();
		currentEvent.Use();
		SceneView.RepaintAll();
	}

	private static void DrawSelectedPositionHandle(
		DVM_DroneCamera drone) {
		if (!drone)
			return;

		int selectedIndex = drone.SelectedPathPointIndex;
		if (selectedIndex < 0 || selectedIndex >= drone.PathPointCount)
			return;

		Vector3 point = drone.GetPathPoint(selectedIndex);
		EditorGUI.BeginChangeCheck();
		Vector3 movedPoint = Handles.PositionHandle(
			point,
			Quaternion.identity);

		if (!EditorGUI.EndChangeCheck())
			return;

		Undo.RecordObject(drone, "Move Drone Path Point");
		drone.SetPathPoint(selectedIndex, movedPoint);
		EditorUtility.SetDirty(drone);
		EditorApplication.QueuePlayerLoopUpdate();
		SceneView.RepaintAll();
	}
}
#endif