#include "common.hlsl"

#pragma kernel Main

// --- dynamically changing vals ---
Texture2D<float4> Camera; // HDR output

Texture2D<uint> IDMapNow; // camera segmentation map
RWTexture2D<uint> IDMapPast; // 1 frame delayed

// x = intensity reference
// y = low pass value Lf
// z = photoreceptor noise
// w = might need it later
RWTexture2D<float4> State;
RWTexture2D<float2> Output; // packed event value
RWTexture2D<float4> Debug;

int iterSeed; // constant for all pixels
uint2 frame; // split ulong in half

// --- consts ---
int EventCountScale;
float dtSecs; // explicitly "secs" because tau is as well
float tauOn;
float tauOff;

//_imperfections_
float leakRateHz;
float leakJitterFraction;
bool addPhotoAndShotNoise;
float photoNoiseVoltage;
float photoNoiseCutoffHz;

Texture2D<float4> ThreshAndNoiseRate;

float luma(float4 col)
{
	return 
		.2126 * max(0., col.r) +
		.7152 * max(0., col.g) +
		.0722 * max(0., col.b);
}

float leakCurrent(inout uint4 seed, float4 threshNoiseRate)
{
/* original from v2e
	rand = torch.randn...
	curr_leak_rate = leak_rate_hz*noise_rate_array*(1-leak_jitter_fraction*rand)
	delta_leak = delta_time*curr_leak_rate*pos_thres
*/
	float rand = boxMullerRandomNormal(seed);
	float curLeakRate = leakRateHz * threshNoiseRate.z * (1 - leakJitterFraction * rand);
	float deltaLeak = dtSecs * curLeakRate * threshNoiseRate.x;
	
	return deltaLeak;
}

// v2e- emulator.py line 698
float photoreceptorNoise(inout uint4 seed, float curPhotoNoise)
{
	if (!addPhotoAndShotNoise)
		return 0;
	
	float noise = photoNoiseVoltage * boxMullerRandomNormal(seed);

	// low_pass_filter(noise, self.photoreceptor_noise_arr, None, delta_time, self.cutoff_hz)
	// based on exact discrete time solution to 1st order RC low pass filter 
	float tau = 1 / (2 * PI * photoNoiseCutoffHz);
	float eps = 1 - exp(-dtSecs / tau); // max=1, no clamp needed
	
	return lerp(curPhotoNoise, noise, eps);
}

[numthreads(8, 8, 1)]
void Main(uint3 id : SV_DispatchThreadID)
{
	uint width, height;
	Camera.GetDimensions(width, height);
	if (id.x >= width || id.y >= height)
		return;
	int3 loc = int3(id.xy, 0);
	uint4 seed = seededcoord2seed(id, iterSeed);

	float I = luma(Camera.Load(loc)); // current luma
	float L = log(max(I, 1e-4)); // linlog was designed for 8 bit color, HDR float color can use pure log
	
	if (frame.x == 0u && frame.y == 0u)
	{
		State[id.xy] = float4(L, L, 0, 0);
		Output[id.xy] = 0;
		return;
	}

	// get references
	float4 state = State.Load(loc);
	
	float ref = state.x; // ref == base_log_frame
	float Lf = state.y; // Lf == low pass filtered L
	float curPhotoNoise = state.z; // cpn = current state of low passed photoreceptor noise 
	
	// low pass filter pixel "motion blur" simulation
	float tau = (L > Lf) ? tauOn : tauOff;
	float alpha = 1 - exp(-dtSecs / tau); // α = 1 - e^(-Δt / τ)
	
	Lf += alpha * (L - Lf); // Lf(t+Δt) = Lf(t) + α(L(t) - Lf(t))
	
	// leak 
	float4 threshNoiseRate = ThreshAndNoiseRate[id.xy];
	float leak = leakCurrent(seed, threshNoiseRate);
	ref -= leak;
	
	// photo noise 
	float photoNoise = photoreceptorNoise(seed, curPhotoNoise);
	
	float diff = Lf + photoNoise - ref;
	
	bool on = diff > 0;
	int polarity = on ? 1 : -1;
	
	// compute the rest
	float ContrastThreshold = on ? threshNoiseRate.x : threshNoiseRate.y;
	
	int numEvents = floor(polarity * diff / ContrastThreshold);
	
	// pack polarity, events, diff into one float
	// TODO: make this more easy to read 
	float event = sign(numEvents) * polarity * (numEvents * EventCountScale + abs(diff));
	
	// event source ; 0-noise event
	bool even = (frame.x & 1u) == 0;
	uint lastID = IDMapPast[id.xy]; 
	uint curID = IDMapNow[id.xy];
	//IDMapPast[id.xy] = IDMapNow[id.xy];
	
	uint srcID = on ? curID : lastID; 
	
	if (!(diff - photoNoise + leak > ContrastThreshold)) // did noise current cause this event?
		// ! would there have been an event if leak and noise were 0?
		srcID = 0;
		
	float meta = asfloat(srcID);
	Output[id.xy] = float2(event, meta);
	
	// update state
	// Lf and photoNoise are low passed
	ref += polarity * numEvents * ContrastThreshold; 
	State[id.xy] = float4(ref, Lf, photoNoise, 0);
	
	Debug[id.xy] = float4(photoNoise, curPhotoNoise, 0, 0);
}