/*
 * NON-HUMAN-GENERATED SOURCE
 * This source file was generated by AI and was not human-generated.
 *
 * Usage:
 * 1. Add DVO_TrafficSimulator to a GameObject and assign a vehicle prefab whose
 *    root contains DVO_Vehicle. Every spawned vehicle receives Init().
 * 2. Add paths in the inspector. Select and drag keypoints in the Scene view;
 *    Shift-click the XZ plane to append points and mark selected points as stops.
 * 3. Set the deterministic seed, prewarm time, duration, spawn settings, and the
 *    two avoidance radii. The slowdown radius must be at least the forced radius.
 * 4. Click Bake Traffic, then use Play/Pause Preview or the preview-time slider.
 * 5. At runtime call UpdateSimulation(double time), or drive UpdateState through
 *    the existing DVObject/Simulated-X timeline integration.
 *
 * Assumptions:
 * - Paths are one-way, open polylines with at least two keypoints.
 * - Motion and simulation state use XZ only; globalY is presentation only.
 * - Prefab renderers define preview bounds and prefab pivots are center-bottom.
 * - Each stop-sign keypoint is serviced once per vehicle.
 * - Avoidance radii are per-vehicle radii, so pair distances use their diameters.
 */

using System;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Serialization;
using System.Linq;

#if UNITY_EDITOR
using UnityEditor;
#endif

[ExecuteAlways]
public sealed class DVO_TrafficSimulator : DVObject {
	#region Serialized Types

	[Serializable]
	public sealed class TrafficKeypoint {
		public Vector2 position;
		public bool stopSign;

		public TrafficKeypoint() { }

		public TrafficKeypoint(Vector2 position) {
			this.position = position;
		}
	}

	[Serializable]
	public sealed class TrafficPath {
		public string name = "Traffic Path";
		public Color color = new Color(0.1f, 0.75f, 1f, 1f);
		public List<TrafficKeypoint> keypoints = new List<TrafficKeypoint>();
	}

	[Serializable]
	private struct BakedSample {
		public double time;
		public Vector2 position;
		public float yaw;
	}

	[Serializable]
	private sealed class BakedVehicle {
		public int id;
		public int pathIndex;
		public double spawnTime;
		public double despawnTime;
		public List<BakedSample> samples = new List<BakedSample>();
	}

	private sealed class BakeVehicleState {
		public BakedVehicle track;
		public bool recorded;
		public float distance;
		public float speed;
		public float preferredSpeed;
		public int nextStopKeypoint;
		public double stoppedUntil = -1.0;
		public bool holdingAtStop;
		public Vector2 position;
		public Vector2 forward;
	}

	private struct Pose2D {
		public Vector2 position;
		public float yaw;
	}

	#endregion

	#region Configuration

	[Header("Source")]
	[SerializeField] private GameObject vehiclePrefab;
	[SerializeField] private Transform vehicleParent;
	[SerializeField] private float globalY;

	[Header("Paths")]
	[SerializeField] private List<TrafficPath> paths = new List<TrafficPath>();

	[Header("Deterministic Bake")]
	[SerializeField] private int seed = 12345;
	[Tooltip("Seconds simulated before baked time zero. The exported bake duration is unchanged.")]
	[Min(0f)] [SerializeField] private float prewarmSeconds;
	[Min(0.1f)] [SerializeField] private float bakeDuration = 30f;
	[Range(1f, 120f)] [SerializeField] private float bakeStepsPerSecond = 30f;
	[SerializeField] private float bakeStepsPerSecondSimulation = 100f;
	[Min(0f)] [SerializeField] private float minimumSpawnInterval = 1.5f;
	[Min(0f)] [SerializeField] private float maximumSpawnInterval = 3.5f;
	[Min(1)] [SerializeField] private int maximumVehicles = 64;

	[Header("Vehicle Motion")]
	[Min(0.01f)] [SerializeField] private float minimumSpeed = 4f;
	[Min(0.01f)] [SerializeField] private float maximumSpeed = 7f;
	[Min(0.01f)] [SerializeField] private float acceleration = 4f;
	[Min(0.01f)] [SerializeField] private float braking = 8f;
	[Tooltip("Hard per-vehicle radius. Overlaps inside twice this radius are resolved by rewinding the yielding vehicle along its path.")]
	[FormerlySerializedAs("separationRadius")]
	[Min(0.01f)] [SerializeField] private float forcedSeparationRadius = 1.5f;
	[Tooltip("Soft per-vehicle radius. A yielding vehicle slows between twice this radius and the forced-separation distance.")]
	[Min(0.01f)] [SerializeField] private float slowdownSuggestionRadius = 3f;
	[Min(0f)] [SerializeField] private float stopDuration = 1f;
	[Min(0.01f)] [SerializeField] private float stopApproachDistance = 5f;

	[Header("Preview")]
	[SerializeField] private bool previewMode;
	[SerializeField, HideInInspector] private double previewTime;
	[SerializeField] private bool drawPaths = true;
	[SerializeField] private bool drawVehicleBounds = true;
	[SerializeField] private bool useDebugExtra = true;
	[SerializeField] private Color boundsColor = new Color(0.2f, 1f, 0.25f, 1f);
	[FormerlySerializedAs("radiusColor")]
	[SerializeField] private Color forcedRadiusColor = new Color(1f, 0.2f, 0.1f, 1f);
	[SerializeField] private Color slowdownRadiusColor = new Color(1f, 0.75f, 0.1f, 1f);

	#endregion

	#region Baked and Runtime State

	[SerializeField, HideInInspector]
	private List<BakedVehicle> bakedVehicles = new List<BakedVehicle>();

	[SerializeField, HideInInspector] private double bakedDuration;
	[SerializeField, HideInInspector] private int selectedPathIndex = -1;
	[SerializeField, HideInInspector] private int selectedPointIndex = -1;

	[NonSerialized]
	private readonly Dictionary<int, DVO_Vehicle> liveVehicles =
		new Dictionary<int, DVO_Vehicle>();

	private Bounds prefabLocalBounds = new Bounds(Vector3.zero, Vector3.one);
	private bool hasPrefabBounds;
	private double currentTime;
	private bool previewPlaying;
	private double previewLastClock;

	public int BakedVehicleCount => bakedVehicles.Count;
	public double BakedDuration => bakedDuration;
	public int PathCount => paths.Count;
	public int SelectedPathIndex => selectedPathIndex;
	public int SelectedPointIndex => selectedPointIndex;
	public float GlobalY => globalY;
	public bool PreviewMode => previewMode;
	public double PreviewTime => previewTime;
	public bool PreviewPlaying => previewPlaying;

	#endregion

	#region Lifecycle and Simulated-X Hook

	private void OnDisable() {
		PausePreview();
		DestroyAllVehicles();
	}

	public override void Init() {
		seed = DVConfig.Seed;
		bakeStepsPerSecond = bakeStepsPerSecondSimulation;
		BakeSimulation();

		CalculatePrefabBounds();
		UpdateSimulation(previewMode ? previewTime : 0.0);
	}

	// Exact timeline-facing signature requested by the Simulated-X baking system.
	public void UpdateSimulation(double time, ulong? srcULtime = null) {
		currentTime = SanitizeTime(time);
		ReconcileVehicles(currentTime, srcULtime ?? (ulong)(time * DVConfig.timeScale));
	}

	public override void UpdateState(ulong time) {
		UpdateSimulation(time / (double)DVConfig.timeScale, time);
	}

	private void Update() {
		if (!previewMode)
			return;

		if (Application.isPlaying)
			TickPreview(Time.realtimeSinceStartupAsDouble);
		else {
			UpdateSimulation(previewTime);
			if (useDebugExtra)
				DrawDebugExtraPreview();
		}
	}

	public void PlayPreview() {
		if (bakedDuration <= 0.0)
			return;

		previewMode = true;
		if (previewTime >= bakedDuration)
			previewTime = 0.0;
		previewPlaying = true;
		previewLastClock = double.NaN;
		UpdateSimulation(previewTime);
	}

	public void PausePreview() {
		previewPlaying = false;
	}

	public void TickPreview(double realtime) {
		if (!previewMode || !previewPlaying || bakedDuration <= 0.0)
			return;
		if (double.IsNaN(previewLastClock)) {
			previewLastClock = realtime;
			return;
		}

		double delta = Math.Max(0.0, realtime - previewLastClock);
		previewLastClock = realtime;
		previewTime = (previewTime + delta) % bakedDuration;
		UpdateSimulation(previewTime);
		if (useDebugExtra)
			DrawDebugExtraPreview();
	}

	#endregion

	#region Deterministic Baking

	public void BakeSimulation() {
		DestroyAllVehicles();
		bakedVehicles.Clear();

		if (vehiclePrefab == null || CountValidPaths() == 0) {
			bakedDuration = 0.0;
			return;
		}

		System.Random random = new System.Random(seed);
		float dt = 1f / Mathf.Max(1f, bakeStepsPerSecond);
		double duration = Math.Max(0.1, bakeDuration);
		double warmup = Math.Max(0.0, prewarmSeconds);
		double simulationEnd = warmup + duration;
		double[] nextSpawnTimes = new double[paths.Count];
		List<BakeVehicleState> active = new List<BakeVehicleState>();
		int nextVehicleId = 1;

		for (int pathIndex = 0; pathIndex < paths.Count; pathIndex++)
			nextSpawnTimes[pathIndex] = NextSpawnDelay(random);

		// Phase one advances [0, warmup) without recording. Phase two continues
		// the same state through [warmup, warmup + duration] and shifts saved
		// timestamps back by warmup so the baked timeline remains [0, duration].
		for (double simulationTime = 0.0;
			simulationTime < simulationEnd - 0.000001;) {
			float stepDt = (float)Math.Min(dt, simulationEnd - simulationTime);
			if (simulationTime < warmup && simulationTime + stepDt > warmup)
				stepDt = (float)(warmup - simulationTime);

			double stepEndSimulationTime = simulationTime + stepDt;
			double recordingTime = simulationTime - warmup;
			double stepEndRecordingTime = stepEndSimulationTime - warmup;
			bool recordingNow = simulationTime >= warmup;

			for (int pathIndex = 0; pathIndex < paths.Count; pathIndex++) {
				if (!IsPathValid(pathIndex) ||
					simulationTime + 0.000001 < nextSpawnTimes[pathIndex])
					continue;

				if (bakedVehicles.Count < maximumVehicles &&
					active.Count < maximumVehicles &&
					CanSpawn(pathIndex, active)) {
					BakeVehicleState spawned = SpawnBakeVehicle(
						pathIndex,
						nextVehicleId++,
						recordingTime,
						duration,
						recordingNow,
						random);
					active.Add(spawned);
					if (spawned.recorded)
						bakedVehicles.Add(spawned.track);
				}

				nextSpawnTimes[pathIndex] =
					simulationTime + NextSpawnDelay(random);
			}

			float[] targetSpeeds = new float[active.Count];
			for (int i = 0; i < active.Count; i++)
				targetSpeeds[i] = ComputeTargetSpeed(
					active[i],
					active,
					simulationTime,
					stepDt);

			for (int i = active.Count - 1; i >= 0; i--) {
				BakeVehicleState vehicle = active[i];
				float rate = targetSpeeds[i] < vehicle.speed ? braking : acceleration;
				vehicle.speed = Mathf.MoveTowards(vehicle.speed, targetSpeeds[i], rate * stepDt);
				vehicle.distance += vehicle.speed * stepDt;
				ClampAtStopSign(vehicle, stepEndSimulationTime);

				float pathLength = GetPathLength(vehicle.track.pathIndex);
				if (vehicle.distance >= pathLength) {
					if (vehicle.recorded)
						vehicle.track.despawnTime =
							Math.Max(0.0, stepEndRecordingTime);
					active.RemoveAt(i);
					continue;
				}

				GetPathPose(vehicle.track.pathIndex, vehicle.distance, out vehicle.position, out vehicle.forward);
			}

			ResolveForcedSeparations(active);

			if (stepEndSimulationTime >= warmup) {
				for (int i = 0; i < active.Count; i++) {
					BakeVehicleState vehicle = active[i];
					if (!vehicle.recorded) {
						vehicle.recorded = true;
						vehicle.track.spawnTime = 0.0;
						vehicle.track.samples.Clear();
						bakedVehicles.Add(vehicle.track);
					}
					vehicle.track.samples.Add(CreateSample(
						Math.Max(0.0, stepEndRecordingTime),
						vehicle.position,
						vehicle.forward));
				}
			}

			simulationTime = stepEndSimulationTime;
		}

		for (int i = 0; i < active.Count; i++)
			active[i].track.despawnTime = duration;

		bakedDuration = duration;
		previewTime = Math.Min(previewTime, bakedDuration);
		CalculatePrefabBounds();
		UpdateSimulation(previewMode ? previewTime : 0.0);
	}

	public void ClearBake() {
		PausePreview();
		DestroyAllVehicles();
		bakedVehicles.Clear();
		bakedDuration = 0.0;
		previewTime = 0.0;
	}

	private BakeVehicleState SpawnBakeVehicle(
		int pathIndex,
		int id,
		double recordingTime,
		double duration,
		bool recordImmediately,
		System.Random random) {
		Vector2 position;
		Vector2 forward;
		GetPathPose(pathIndex, 0f, out position, out forward);

		BakedVehicle track = new BakedVehicle {
			id = id,
			pathIndex = pathIndex,
			spawnTime = recordImmediately ? Math.Max(0.0, recordingTime) : 0.0,
			despawnTime = duration
		};
		if (recordImmediately)
			track.samples.Add(CreateSample(recordingTime, position, forward));

		return new BakeVehicleState {
			track = track,
			recorded = recordImmediately,
			position = position,
			forward = forward,
			preferredSpeed = Mathf.Lerp(minimumSpeed, maximumSpeed, NextFloat(random)),
			speed = 0f
		};
	}

	private float ComputeTargetSpeed(
		BakeVehicleState vehicle,
		List<BakeVehicleState> active,
		double time,
		float dt) {
		float target = vehicle.preferredSpeed;
		TrafficPath path = paths[vehicle.track.pathIndex];

		if (vehicle.stoppedUntil > time) {
			vehicle.holdingAtStop = true;
			return 0f;
		}
		vehicle.holdingAtStop = false;

		while (vehicle.nextStopKeypoint < path.keypoints.Count &&
			!path.keypoints[vehicle.nextStopKeypoint].stopSign) {
			vehicle.nextStopKeypoint++;
		}

		if (vehicle.nextStopKeypoint < path.keypoints.Count) {
			float stopDistance = GetDistanceAtKeypoint(
				vehicle.track.pathIndex,
				vehicle.nextStopKeypoint);
			float remaining = stopDistance - vehicle.distance;

			if (remaining <= 0.05f)
				return 0f;
			if (remaining < stopApproachDistance) {
				target = Mathf.Min(target, Mathf.Max(0f, remaining / Mathf.Max(dt, 0.0001f)));
			}
		}

		float forcedDistance = forcedSeparationRadius * 2f;
		float slowdownDistance = slowdownSuggestionRadius * 2f;
		for (int i = 0; i < active.Count; i++) {
			BakeVehicleState other = active[i];
			if (ReferenceEquals(vehicle, other))
				continue;

			Vector2 offset = other.position - vehicle.position;
			float distance = offset.magnitude;
			if (distance >= slowdownDistance)
				continue;

			bool samePathAhead =
				vehicle.track.pathIndex == other.track.pathIndex &&
				Vector2.Dot(vehicle.forward, offset) > 0f;
			bool crossPathYield =
				vehicle.track.pathIndex != other.track.pathIndex &&
				(other.stoppedUntil > time || vehicle.track.id > other.track.id);

			if (samePathAhead || crossPathYield) {
				float suggestion = Mathf.InverseLerp(forcedDistance, slowdownDistance, distance);
				target = Mathf.Min(target, vehicle.preferredSpeed * suggestion);
			}
		}

		return target;
	}

	private void ClampAtStopSign(BakeVehicleState vehicle, double time) {
		TrafficPath path = paths[vehicle.track.pathIndex];
		while (vehicle.nextStopKeypoint < path.keypoints.Count &&
			!path.keypoints[vehicle.nextStopKeypoint].stopSign) {
			vehicle.nextStopKeypoint++;
		}

		if (vehicle.nextStopKeypoint >= path.keypoints.Count)
			return;

		float stopDistance = GetDistanceAtKeypoint(
			vehicle.track.pathIndex,
			vehicle.nextStopKeypoint);
		if (vehicle.distance < stopDistance)
			return;

		vehicle.distance = stopDistance;
		vehicle.speed = 0f;
		vehicle.stoppedUntil = time + stopDuration;
		vehicle.holdingAtStop = true;
		vehicle.nextStopKeypoint++;
	}

	private void ResolveForcedSeparations(List<BakeVehicleState> active) {
		float forcedDistance = forcedSeparationRadius * 2f;
		for (int pass = 0; pass < active.Count; pass++) {
			bool resolvedAny = false;
			for (int a = 0; a < active.Count; a++) {
				for (int b = a + 1; b < active.Count; b++) {
					BakeVehicleState first = active[a];
					BakeVehicleState second = active[b];
					if (Vector2.Distance(first.position, second.position) >= forcedDistance)
						continue;

					BakeVehicleState yielding = ChooseYieldingVehicle(first, second);
					BakeVehicleState holding = ReferenceEquals(yielding, first) ? second : first;
					if (yielding.distance <= 0f && holding.distance > 0f) {
						BakeVehicleState swap = yielding;
						yielding = holding;
						holding = swap;
					}
					RewindToForcedDistance(yielding, holding, forcedDistance);
					if (Vector2.Distance(yielding.position, holding.position) < forcedDistance &&
						holding.distance > 0f) {
						RewindToForcedDistance(holding, yielding, forcedDistance);
					}
					resolvedAny = true;
				}
			}
			if (!resolvedAny)
				break;
		}
	}

	private static BakeVehicleState ChooseYieldingVehicle(
		BakeVehicleState first,
		BakeVehicleState second) {
		if (first.holdingAtStop != second.holdingAtStop)
			return first.holdingAtStop ? second : first;
		if (first.track.pathIndex == second.track.pathIndex) {
			if (!Mathf.Approximately(first.distance, second.distance))
				return first.distance < second.distance ? first : second;
		}
		return first.track.id > second.track.id ? first : second;
	}

	private void RewindToForcedDistance(
		BakeVehicleState yielding,
		BakeVehicleState holding,
		float forcedDistance) {
		float step = Mathf.Max(0.025f, forcedDistance / 12f);
		float candidateDistance = yielding.distance;
		while (Vector2.Distance(yielding.position, holding.position) < forcedDistance &&
			candidateDistance > 0f) {
			candidateDistance = Mathf.Max(0f, candidateDistance - step);
			Vector2 candidatePosition;
			Vector2 candidateForward;
			GetPathPose(
				yielding.track.pathIndex,
				candidateDistance,
				out candidatePosition,
				out candidateForward);
			yielding.distance = candidateDistance;
			yielding.position = candidatePosition;
			yielding.forward = candidateForward;
		}

		yielding.speed = 0f;
	}

	private bool CanSpawn(int pathIndex, List<BakeVehicleState> active) {
		Vector2 start = paths[pathIndex].keypoints[0].position;
		float minimumDistance = forcedSeparationRadius * 2f;
		for (int i = 0; i < active.Count; i++) {
			if (Vector2.Distance(start, active[i].position) < minimumDistance)
				return false;
		}
		return true;
	}

	private double NextSpawnDelay(System.Random random) {
		float low = Mathf.Min(minimumSpawnInterval, maximumSpawnInterval);
		float high = Mathf.Max(minimumSpawnInterval, maximumSpawnInterval);
		return Math.Max(1.0 / Math.Max(1.0, bakeStepsPerSecond), Mathf.Lerp(low, high, NextFloat(random)));
	}

	private static float NextFloat(System.Random random) {
		return (float)random.NextDouble();
	}

	private static BakedSample CreateSample(double time, Vector2 position, Vector2 forward) {
		return new BakedSample {
			time = time,
			position = position,
			yaw = Mathf.Atan2(forward.x, forward.y) * Mathf.Rad2Deg
		};
	}

	#endregion

	#region Runtime Reconciliation and Interpolation

	private void ReconcileVehicles(double time, ulong ultime) {
		HashSet<int> required = new HashSet<int>();

		for (int i = 0; i < bakedVehicles.Count; i++) {
			BakedVehicle track = bakedVehicles[i];
			if (track.samples.Count == 0 || time < track.spawnTime || time > track.despawnTime)
				continue;

			required.Add(track.id);
			if (!liveVehicles.TryGetValue(track.id, out DVO_Vehicle vehicle) || vehicle == null) {
				vehicle = InstantiateVehicle(track.id);
				if (vehicle == null)
					continue;
				liveVehicles[track.id] = vehicle;
			}

			Pose2D pose = EvaluateTrack(track, time);
			vehicle.transform.SetPositionAndRotation(
				ToWorld(pose.position),
				Quaternion.Euler(0f, pose.yaw, 0f));

			vehicle.UpdateModel();

			// TODO:xx
			vehicle.UpdateState(ultime); // should the dvmanager track these and update them there instead?
			// we should fix this later 
		}

		List<int> stale = new();
		foreach (KeyValuePair<int, DVO_Vehicle> pair in liveVehicles) {
			if (!required.Contains(pair.Key) || pair.Value == null)
				stale.Add(pair.Key);
		}

		for (int i = 0; i < stale.Count; i++)
			DestroyVehicle(stale[i]);
	}

	private DVO_Vehicle InstantiateVehicle(int id) {
		if (vehiclePrefab == null)
			return null;

		GameObject instance = Instantiate(vehiclePrefab, vehicleParent);
		instance.name = vehiclePrefab.name + " [Traffic " + id + "]";
		if (!Application.isPlaying)
			instance.hideFlags = HideFlags.DontSave;

		DVO_Vehicle vehicle = instance.GetComponent<DVO_Vehicle>();
		if (vehicle == null) {
			DestroyObjectDynamic(instance);
			Debug.LogError("Traffic vehicle prefab root must contain DVO_Vehicle.", this);
			return null;
		}

		vehicle.Init();
		return vehicle;
	}

	private Pose2D EvaluateTrack(BakedVehicle track, double time) {
		if (time <= track.samples[0].time)
			return SampleToPose(track.samples[0]);

		int last = track.samples.Count - 1;
		if (time >= track.samples[last].time)
			return SampleToPose(track.samples[last]);

		int low = 0;
		int high = last;
		while (low + 1 < high) {
			int middle = (low + high) / 2;
			if (track.samples[middle].time <= time)
				low = middle;
			else
				high = middle;
		}

		BakedSample a = track.samples[low];
		BakedSample b = track.samples[high];
		float blend = (float)((time - a.time) / Math.Max(0.000001, b.time - a.time));
		return new Pose2D {
			position = Vector2.Lerp(a.position, b.position, blend),
			yaw = Mathf.LerpAngle(a.yaw, b.yaw, blend)
		};
	}

	private static Pose2D SampleToPose(BakedSample sample) {
		return new Pose2D { position = sample.position, yaw = sample.yaw };
	}

	private void DestroyVehicle(int id) {
		DVO_Vehicle vehicle;
		if (!liveVehicles.TryGetValue(id, out vehicle))
			return;
		liveVehicles.Remove(id);
		if (vehicle != null)
			DestroyObjectDynamic(vehicle.gameObject);
	}

	private void DestroyAllVehicles() {
		foreach (DVO_Vehicle vehicle in liveVehicles.Values) {
			if (vehicle != null)
				DestroyObjectDynamic(vehicle.gameObject);
		}
		liveVehicles.Clear();

		foreach (Transform obj in vehicleParent)
			DestroyObjectDynamic(obj.gameObject);
	}

	private static void DestroyObjectDynamic(UnityEngine.Object target) {
		if (Application.isPlaying)
			Destroy(target);
		else
			DestroyImmediate(target);
	}

	#endregion

	#region Path Sampling and Editing

	public int GetPointCount(int pathIndex) {
		return IsPathIndexValid(pathIndex) ? paths[pathIndex].keypoints.Count : 0;
	}

	public Vector3 GetPointWorld(int pathIndex, int pointIndex) {
		Vector2 point = paths[pathIndex].keypoints[pointIndex].position;
		return ToWorld(point);
	}

	public bool IsStopSign(int pathIndex, int pointIndex) {
		return paths[pathIndex].keypoints[pointIndex].stopSign;
	}

	public Color GetPathColor(int pathIndex) {
		return paths[pathIndex].color;
	}

	public void SelectPoint(int pathIndex, int pointIndex) {
		selectedPathIndex = pathIndex;
		selectedPointIndex = pointIndex;
	}

	public void SetPointWorld(int pathIndex, int pointIndex, Vector3 world) {
		paths[pathIndex].keypoints[pointIndex].position = new Vector2(world.x, world.z);
	}

	public void AddPath() {
		TrafficPath path = new TrafficPath { name = "Traffic Path " + (paths.Count + 1) };
		Vector2 origin = new Vector2(transform.position.x, transform.position.z);
		path.keypoints.Add(new TrafficKeypoint(origin));
		path.keypoints.Add(new TrafficKeypoint(origin + Vector2.up * 10f));
		paths.Add(path);
		SelectPoint(paths.Count - 1, 1);
	}

	public void AppendPointToSelectedPath(Vector3 world) {
		if (!IsPathIndexValid(selectedPathIndex))
			return;
		paths[selectedPathIndex].keypoints.Add(
			new TrafficKeypoint(new Vector2(world.x, world.z)));
		selectedPointIndex = paths[selectedPathIndex].keypoints.Count - 1;
	}

	public void RemoveSelectedPoint() {
		if (!IsSelectedPointValid())
			return;
		paths[selectedPathIndex].keypoints.RemoveAt(selectedPointIndex);
		selectedPointIndex = Mathf.Min(selectedPointIndex, GetPointCount(selectedPathIndex) - 1);
	}

	public void ToggleSelectedStopSign() {
		if (IsSelectedPointValid())
			paths[selectedPathIndex].keypoints[selectedPointIndex].stopSign =
				!paths[selectedPathIndex].keypoints[selectedPointIndex].stopSign;
	}

	public void SetPreview(bool enabled, double time) {
		previewMode = enabled;
		previewTime = Math.Min(SanitizeTime(time), bakedDuration);
		previewLastClock = double.NaN;
		if (!previewMode) {
			PausePreview();
			DestroyAllVehicles();
		} else {
			UpdateSimulation(previewTime);
		}
	}

	private bool IsSelectedPointValid() {
		return IsPathIndexValid(selectedPathIndex) &&
			selectedPointIndex >= 0 &&
			selectedPointIndex < paths[selectedPathIndex].keypoints.Count;
	}

	private bool IsPathIndexValid(int index) {
		return index >= 0 && index < paths.Count && paths[index] != null;
	}

	private bool IsPathValid(int index) {
		return IsPathIndexValid(index) && paths[index].keypoints != null && paths[index].keypoints.Count >= 2;
	}

	private int CountValidPaths() {
		int count = 0;
		for (int i = 0; i < paths.Count; i++)
			if (IsPathValid(i)) count++;
		return count;
	}

	private float GetPathLength(int pathIndex) {
		float length = 0f;
		List<TrafficKeypoint> points = paths[pathIndex].keypoints;
		for (int i = 1; i < points.Count; i++)
			length += Vector2.Distance(points[i - 1].position, points[i].position);
		return length;
	}

	private float GetDistanceAtKeypoint(int pathIndex, int keypointIndex) {
		float distance = 0f;
		List<TrafficKeypoint> points = paths[pathIndex].keypoints;
		for (int i = 1; i <= keypointIndex && i < points.Count; i++)
			distance += Vector2.Distance(points[i - 1].position, points[i].position);
		return distance;
	}

	private void GetPathPose(int pathIndex, float distance, out Vector2 position, out Vector2 forward) {
		List<TrafficKeypoint> points = paths[pathIndex].keypoints;
		float remaining = Mathf.Max(0f, distance);

		for (int i = 1; i < points.Count; i++) {
			Vector2 a = points[i - 1].position;
			Vector2 b = points[i].position;
			float segmentLength = Vector2.Distance(a, b);
			if (remaining <= segmentLength || i == points.Count - 1) {
				forward = segmentLength > 0.0001f ? (b - a) / segmentLength : Vector2.up;
				position = Vector2.Lerp(a, b, Mathf.Clamp01(remaining / Mathf.Max(segmentLength, 0.0001f)));
				return;
			}
			remaining -= segmentLength;
		}

		position = points[points.Count - 1].position;
		forward = Vector2.up;
	}

	private Vector3 ToWorld(Vector2 point) {
		return new Vector3(point.x, globalY, point.y);
	}

	private double SanitizeTime(double time) {
		if (double.IsNaN(time) || double.IsInfinity(time))
			return 0.0;
		return Math.Max(0.0, time);
	}

	#endregion

	#region Bounds Preview and Gizmos

	private void CalculatePrefabBounds() {
		hasPrefabBounds = false;
		if (vehiclePrefab == null)
			return;

		Renderer[] renderers = vehiclePrefab.GetComponentsInChildren<Renderer>(true);
		Matrix4x4 rootToLocal = vehiclePrefab.transform.worldToLocalMatrix;
		for (int i = 0; i < renderers.Length; i++) {
			Bounds local = renderers[i].localBounds;
			Matrix4x4 matrix = rootToLocal * renderers[i].transform.localToWorldMatrix;
			EncapsulateTransformedBounds(local, matrix, ref prefabLocalBounds, ref hasPrefabBounds);
		}

		if (!hasPrefabBounds) {
			prefabLocalBounds = new Bounds(Vector3.up * 0.5f, Vector3.one);
			hasPrefabBounds = true;
		}
	}

	private static void EncapsulateTransformedBounds(
		Bounds source,
		Matrix4x4 matrix,
		ref Bounds result,
		ref bool initialized) {
		Vector3 min = source.min;
		Vector3 max = source.max;
		for (int x = 0; x < 2; x++)
			for (int y = 0; y < 2; y++)
				for (int z = 0; z < 2; z++) {
					Vector3 corner = new Vector3(x == 0 ? min.x : max.x, y == 0 ? min.y : max.y, z == 0 ? min.z : max.z);
					Vector3 point = matrix.MultiplyPoint3x4(corner);
					if (!initialized) {
						result = new Bounds(point, Vector3.zero);
						initialized = true;
					} else {
						result.Encapsulate(point);
					}
				}
	}

	private void OnDrawGizmos() {
		if (drawPaths)
			DrawPathGizmos();
		if (previewMode && drawVehicleBounds)
			DrawBakedVehicleGizmos(previewTime);
	}

	private void DrawPathGizmos() {
		for (int pathIndex = 0; pathIndex < paths.Count; pathIndex++) {
			if (!IsPathIndexValid(pathIndex) || paths[pathIndex].keypoints == null)
				continue;
			TrafficPath path = paths[pathIndex];
			Gizmos.color = path.color;
			for (int i = 0; i < path.keypoints.Count; i++) {
				Vector3 point = ToWorld(path.keypoints[i].position);
				Gizmos.DrawSphere(point, 0.15f);
				if (i > 0)
					Gizmos.DrawLine(ToWorld(path.keypoints[i - 1].position), point);
				if (path.keypoints[i].stopSign) {
					Gizmos.color = Color.red;
					Gizmos.DrawCube(point + Vector3.up * 0.45f, new Vector3(0.55f, 0.9f, 0.08f));
					Gizmos.color = path.color;
				}
			}
		}
	}

	private void DrawBakedVehicleGizmos(double time) {
		if (!hasPrefabBounds)
			CalculatePrefabBounds();

		for (int i = 0; i < bakedVehicles.Count; i++) {
			BakedVehicle track = bakedVehicles[i];
			if (track.samples.Count == 0 || time < track.spawnTime || time > track.despawnTime)
				continue;

			Pose2D pose = EvaluateTrack(track, time);
			Matrix4x4 previous = Gizmos.matrix;
			Gizmos.matrix = Matrix4x4.TRS(ToWorld(pose.position), Quaternion.Euler(0f, pose.yaw, 0f), Vector3.one);
			Gizmos.color = boundsColor;
			Gizmos.DrawWireCube(prefabLocalBounds.center, prefabLocalBounds.size);
			Gizmos.matrix = previous;

			Gizmos.color = slowdownRadiusColor;
			Gizmos.DrawWireSphere(ToWorld(pose.position), slowdownSuggestionRadius);
			Gizmos.color = forcedRadiusColor;
			Gizmos.DrawWireSphere(ToWorld(pose.position), forcedSeparationRadius);
		}
	}

	private void DrawDebugExtraPreview() {
		if (!drawVehicleBounds)
			return;

		for (int i = 0; i < bakedVehicles.Count; i++) {
			BakedVehicle track = bakedVehicles[i];
			if (track.samples.Count == 0 || currentTime < track.spawnTime || currentTime > track.despawnTime)
				continue;

			Pose2D pose = EvaluateTrack(track, currentTime);
			Vector3 center = ToWorld(pose.position) + Quaternion.Euler(0f, pose.yaw, 0f) * prefabLocalBounds.center;
			Vector3 half = prefabLocalBounds.extents;
			DebugExtra.DrawCube(center - half, center + half, boundsColor, 0f, true, false);
			DebugExtra.DrawSphere(
				ToWorld(pose.position),
				slowdownSuggestionRadius,
				24,
				slowdownRadiusColor,
				0f,
				true,
				false);
			DebugExtra.DrawSphere(
				ToWorld(pose.position),
				forcedSeparationRadius,
				24,
				forcedRadiusColor,
				0f,
				true,
				false);
		}
	}

	#endregion

	#region Validation

	private void OnValidate() {
		if (paths == null)
			paths = new List<TrafficPath>();
		if (bakedVehicles == null)
			bakedVehicles = new List<BakedVehicle>();
		for (int i = 0; i < paths.Count; i++) {
			if (paths[i] == null)
				continue;
			if (paths[i].keypoints == null)
				paths[i].keypoints = new List<TrafficKeypoint>();
			for (int j = 0; j < paths[i].keypoints.Count; j++) {
				if (paths[i].keypoints[j] == null)
					paths[i].keypoints[j] = new TrafficKeypoint(Vector2.zero);
			}
		}
		if (!IsPathIndexValid(selectedPathIndex)) {
			selectedPathIndex = -1;
			selectedPointIndex = -1;
		} else if (selectedPointIndex >= paths[selectedPathIndex].keypoints.Count) {
			selectedPointIndex = -1;
		}

		bakeDuration = Mathf.Max(0.1f, bakeDuration);
		prewarmSeconds = Mathf.Max(0f, prewarmSeconds);
		bakeStepsPerSecond = Mathf.Clamp(bakeStepsPerSecond, 1f, 120f);
		minimumSpawnInterval = Mathf.Max(0f, minimumSpawnInterval);
		maximumSpawnInterval = Mathf.Max(minimumSpawnInterval, maximumSpawnInterval);
		maximumVehicles = Mathf.Max(1, maximumVehicles);
		minimumSpeed = Mathf.Max(0.01f, minimumSpeed);
		maximumSpeed = Mathf.Max(minimumSpeed, maximumSpeed);
		forcedSeparationRadius = Mathf.Max(0.01f, forcedSeparationRadius);
		slowdownSuggestionRadius = Mathf.Max(forcedSeparationRadius, slowdownSuggestionRadius);
		stopApproachDistance = Mathf.Max(0.01f, stopApproachDistance);
		previewTime = Math.Min(SanitizeTime(previewTime), bakedDuration);
		CalculatePrefabBounds();
	}

	#endregion

	public override DVObject[] GetSubObjects() => liveVehicles.Values.ToArray();

	public override DVSMemory.InterBBox GenerateBBoxExact(Camera camera) => null;
}

#if UNITY_EDITOR
[CustomEditor(typeof(DVO_TrafficSimulator))]
public sealed class DVM_TrafficSimulatorEditor : Editor {
	private DVO_TrafficSimulator Simulator => (DVO_TrafficSimulator)target;

	private void OnEnable() {
		EditorApplication.update += TickEditorPreview;
	}

	private void OnDisable() {
		EditorApplication.update -= TickEditorPreview;
		if (target != null)
			Simulator.PausePreview();
	}

	public override void OnInspectorGUI() {
		bool wasPreviewing = Simulator.PreviewMode;
		DrawDefaultInspector();
		if (wasPreviewing != Simulator.PreviewMode)
			Simulator.SetPreview(Simulator.PreviewMode, Simulator.PreviewTime);
		EditorGUILayout.Space();

		if (GUILayout.Button("Add Traffic Path")) {
			Undo.RecordObject(Simulator, "Add Traffic Path");
			Simulator.AddPath();
			Changed();
		}

		using (new EditorGUI.DisabledScope(Simulator.SelectedPathIndex < 0)) {
			EditorGUILayout.BeginHorizontal();
			if (GUILayout.Button("Append Point")) {
				Undo.RecordObject(Simulator, "Append Traffic Point");
				int count = Simulator.GetPointCount(Simulator.SelectedPathIndex);
				Vector3 point = count > 0
					? Simulator.GetPointWorld(Simulator.SelectedPathIndex, count - 1)
					: new Vector3(Simulator.transform.position.x, Simulator.GlobalY, Simulator.transform.position.z);
				Simulator.AppendPointToSelectedPath(point + Vector3.forward * 5f);
				Changed();
			}
			if (GUILayout.Button("Toggle Stop Sign")) {
				Undo.RecordObject(Simulator, "Toggle Traffic Stop Sign");
				Simulator.ToggleSelectedStopSign();
				Changed();
			}
			if (GUILayout.Button("Remove Point")) {
				Undo.RecordObject(Simulator, "Remove Traffic Point");
				Simulator.RemoveSelectedPoint();
				Changed();
			}
			EditorGUILayout.EndHorizontal();
		}

		EditorGUILayout.Space();
		EditorGUILayout.BeginHorizontal();
		if (GUILayout.Button("Bake Traffic")) {
			Undo.RecordObject(Simulator, "Bake Traffic Simulation");
			Simulator.BakeSimulation();
			Changed();
		}
		if (GUILayout.Button("Clear Bake")) {
			Undo.RecordObject(Simulator, "Clear Traffic Bake");
			Simulator.ClearBake();
			Changed();
		}
		EditorGUILayout.EndHorizontal();

		EditorGUILayout.LabelField("Baked Vehicles", Simulator.BakedVehicleCount.ToString());
		EditorGUILayout.LabelField("Baked Duration", Simulator.BakedDuration.ToString("0.###") + " s");

		using (new EditorGUI.DisabledScope(Simulator.BakedDuration <= 0.0)) {
			EditorGUILayout.BeginHorizontal();
			if (GUILayout.Button(Simulator.PreviewPlaying ? "Pause Preview" : "Play Preview")) {
				if (Simulator.PreviewPlaying)
					Simulator.PausePreview();
				else
					Simulator.PlayPreview();
				Changed();
			}
			if (GUILayout.Button("Clear Preview")) {
				Simulator.SetPreview(false, 0.0);
				Changed();
			}
			if (GUILayout.Button("Restart Preview")) {
				Simulator.SetPreview(true, 0.0);
				Simulator.PlayPreview();
				Changed();
			}
			EditorGUILayout.EndHorizontal();
		}

		EditorGUI.BeginChangeCheck();
		double preview = EditorGUILayout.Slider(
			"Preview Time",
			(float)Simulator.PreviewTime,
			0f,
			(float)Simulator.BakedDuration);
		if (EditorGUI.EndChangeCheck()) {
			Undo.RecordObject(Simulator, "Change Traffic Preview Time");
			Simulator.SetPreview(true, preview);
			Changed();
		}

		EditorGUILayout.HelpBox(
			"Scene controls: click a point to select it, drag the position handle, or Shift-click the XZ plane to append a point to the selected path.",
			MessageType.Info);
	}

	private void OnSceneGUI() {
		var current = UnityEngine.Event.current;
		for (int pathIndex = 0; pathIndex < Simulator.PathCount; pathIndex++) {
			for (int pointIndex = 0; pointIndex < Simulator.GetPointCount(pathIndex); pointIndex++) {
				Vector3 point = Simulator.GetPointWorld(pathIndex, pointIndex);
				float size = HandleUtility.GetHandleSize(point) * 0.08f;
				Handles.color = Simulator.IsStopSign(pathIndex, pointIndex)
					? Color.red
					: Simulator.GetPathColor(pathIndex);

				if (Handles.Button(point, Quaternion.identity, size, size * 1.3f, Handles.SphereHandleCap)) {
					Simulator.SelectPoint(pathIndex, pointIndex);
					Changed();
				}
			}
		}

		if (Simulator.SelectedPathIndex >= 0 && Simulator.SelectedPointIndex >= 0) {
			Vector3 selected = Simulator.GetPointWorld(Simulator.SelectedPathIndex, Simulator.SelectedPointIndex);
			EditorGUI.BeginChangeCheck();
			Vector3 moved = Handles.PositionHandle(selected, Quaternion.identity);
			if (EditorGUI.EndChangeCheck()) {
				Undo.RecordObject(Simulator, "Move Traffic Point");
				moved.y = Simulator.GlobalY;
				Simulator.SetPointWorld(Simulator.SelectedPathIndex, Simulator.SelectedPointIndex, moved);
				Changed();
			}
		}

		if (current.type == EventType.MouseDown && current.button == 0 && current.shift &&
			!current.alt && Simulator.SelectedPathIndex >= 0) {
			Plane plane = new Plane(Vector3.up, new Vector3(0f, Simulator.GlobalY, 0f));
			Ray ray = HandleUtility.GUIPointToWorldRay(current.mousePosition);
			float enter;
			if (plane.Raycast(ray, out enter)) {
				Undo.RecordObject(Simulator, "Append Traffic Point");
				Simulator.AppendPointToSelectedPath(ray.GetPoint(enter));
				current.Use();
				Changed();
			}
		}
	}

	private void Changed() {
		EditorUtility.SetDirty(Simulator);
		EditorApplication.QueuePlayerLoopUpdate();
		SceneView.RepaintAll();
	}

	private void TickEditorPreview() {
		if (Application.isPlaying || target == null || !Simulator.PreviewPlaying)
			return;

		Simulator.TickPreview(EditorApplication.timeSinceStartup);
		Repaint();
		SceneView.RepaintAll();
	}
}
#endif