// Unity 2022.3+ / URP 14
// Put this file anywhere under an Editor folder.

/*
 * CREATE URP MATERIALS FROM TEXTURES
 * Unity 2022.3+ / Universal Render Pipeline 14
 *
 * AUTHORSHIP
 * This source file was generated by an AI system. It was not human-written.
 * Review and test it in a copy of the project before using it on important assets.
 *
 * INSTALLATION
 * Place this file anywhere inside an Editor folder in the Unity project, for example:
 *
 *     Assets/Editor/CreateUrpMaterialsFromTextures.cs
 *
 * USAGE
 * 1. Select one texture, several related textures, or a folder containing textures.
 * 2. Run Assets > Create URP Materials from Textures.
 * 3. The tool groups recognized PBR maps and creates or updates URP Lit materials.
 *
 * OUTPUT
 * Each source-texture folder receives:
 *
 *     Materials/           Created or updated .mat assets.
 *     Generated Textures/  Channel-packed, opacity-combined, or converted textures.
 *
 * SINGLE-TEXTURE BEHAVIOUR
 * When exactly one selected texture has no recognized map suffix, the texture is used
 * directly as the Base Map. The material uses the exact source filename without its
 * extension and defaults to the specular workflow. This fallback is intentionally not
 * applied to unrecognized files in multi-texture selections.
 *
 * MAP RECOGNITION AND GROUPING
 * Map names are recognized from common token-based aliases, including base color,
 * albedo, diffuse, normal, roughness, smoothness, metallic, metalness, specular,
 * ambient occlusion, opacity, alpha, emission, displacement, ARM, ORM, RMA, and MRA.
 * Resolution, format, and version tokens such as 1K, 2K, JPG, EXR, and V2 are removed
 * when deriving the material name. Unclassified files are ignored unless the single-
 * texture fallback applies. When duplicate maps exist, higher-quality file formats and
 * then larger image dimensions are preferred.
 *
 * MATERIAL WORKFLOW
 * Materials use Universal Render Pipeline/Lit. Specular workflow is assumed unless a
 * metallic or metalness source exists, in which case metallic workflow is used.
 * Roughness is inverted into smoothness. Metallic materials receive a generated URP
 * mask with R = metallic, G = occlusion, B = unused, and A = smoothness. Existing ARM,
 * ORM, RMA, and MRA maps are accepted as inputs and converted to the URP layout; a
 * redundant ARM output is not generated. Specular materials receive a generated
 * specular/smoothness texture only when the available inputs require one.
 *
 * OPACITY
 * A separate opacity or alpha map is combined with the Base Map. Nearly binary opacity
 * becomes alpha clipping; graded opacity becomes a transparent material. The combined
 * Base Map is written under Generated Textures and assigned to the material.
 *
 * NORMAL MAP CONVENTIONS
 * GL, OpenGL, OGL, DX, DXN, and DirectX suffixes are detected. The constant
 * TargetNormalConvention controls the required output convention and currently targets
 * DirectX. If the detected source convention differs, the green channel is inverted,
 * a converted _NormalDX or _NormalGL PNG is created under Generated Textures, and that
 * generated texture is assigned to the material. Unsuffixed normals are assumed to
 * already match the configured target. Source importer settings are restored after a
 * conversion.
 *
 * IMPORT SIDE EFFECTS AND RERUNS
 * The tool corrects source texture type and sRGB settings where required. CPU pixel
 * access can temporarily enable texture readability, causing source reimports. Each
 * generated PNG is also imported and configured. Large selections or high-resolution
 * textures can therefore take time. Generated textures are ignored during later scans,
 * existing generated files are overwritten, and existing materials are updated rather
 * than duplicated.
 */

using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using UnityEditor;
using UnityEngine;
using UnityEngine.Rendering;
using Object = UnityEngine.Object;

public static class CreateMaterialsFromTextures {
	private const string MenuPath = "Assets/Create URP Materials from Textures";
	private const string MaterialsFolderName = "Materials";
	private const string GeneratedFolderName = "Generated Textures";

	// Change this one setting if the target shader/project expects OpenGL (Y+)
	// tangent-space normals instead of DirectX (Y-).
	private const NormalConvention TargetNormalConvention = NormalConvention.DirectX;

	private enum MapKind {
		Albedo, Normal, Roughness, Smoothness, Metallic, Specular,
		Occlusion, Opacity, Emission, Height, Packed
	}

	private enum PackedLayout { None, ARM, ORM, RMA, MRA }
	private enum SourceChannel { Red, Green, Blue, Alpha }
	private enum NormalConvention { Unknown, OpenGL, DirectX }

	private sealed class MapInfo {
		public Texture2D Texture;
		public MapKind Kind;
		public string Key;
		public string DisplayName;
		public string Directory;
		public PackedLayout Layout;
		public NormalConvention NormalConvention;
	}

	private sealed class TextureSet {
		public string Key;
		public string DisplayName;
		public string Directory;
		public readonly Dictionary<MapKind, MapInfo> Maps = new Dictionary<MapKind, MapInfo>();

		public MapInfo Get(MapKind kind) {
			MapInfo value;
			return Maps.TryGetValue(kind, out value) ? value : null;
		}
	}

	private struct PixelSource {
		public MapInfo Map;
		public SourceChannel Channel;
		public bool Invert;

		public bool Exists { get { return Map != null && Map.Texture != null; } }
	}

	private sealed class NameRule {
		public readonly MapKind Kind;
		public readonly string[][] Aliases;
		public readonly PackedLayout Layout;

		public NameRule(MapKind kind, params string[][] aliases) {
			Kind = kind;
			Aliases = aliases;
			Layout = PackedLayout.None;
		}

		public NameRule(PackedLayout layout, params string[][] aliases) {
			Kind = MapKind.Packed;
			Aliases = aliases;
			Layout = layout;
		}
	}

	// Longer aliases are checked first. Recognition is token-based, so a model named
	// "metal_trash_can" is not mistaken for a metalness map when it also has "diff".
	private static readonly NameRule[] Rules =
	{
		new NameRule(MapKind.Albedo,
			A("base", "color"), A("base", "colour"), A("diffuse"), A("albedo"),
			A("diff"), A("color"), A("colour"), A("col")),
		new NameRule(MapKind.Normal,
			A("normal", "direct", "x"), A("normal", "directx"), A("normal", "dx"), A("normal", "dxn"),
			A("normal", "open", "gl"), A("normal", "opengl"), A("normal", "ogl"), A("normal", "gl"),
			A("nor", "dx"), A("nor", "dxn"), A("nor", "gl"), A("nor", "ogl"), A("normal"),
			A("norm"), A("nrm"), A("nor")),
		new NameRule(MapKind.Roughness, A("roughness"), A("rough"), A("rgh")),
		new NameRule(MapKind.Smoothness, A("smoothness"), A("smooth"), A("glossiness"), A("gloss")),
		new NameRule(MapKind.Metallic, A("metalness"), A("metallic"), A("metal"), A("mtl")),
		new NameRule(MapKind.Specular, A("specular"), A("spec")),
		new NameRule(MapKind.Occlusion,
			A("ambient", "occlusion"), A("ambientocclusion"), A("occlusion"), A("ao")),
		new NameRule(MapKind.Opacity,
			A("opacity"), A("transparency"), A("transparent"), A("alpha"), A("cutout")),
		new NameRule(MapKind.Emission, A("emission"), A("emissive"), A("emit")),
		new NameRule(MapKind.Height, A("displacement"), A("displace"), A("height"), A("disp")),
		new NameRule(PackedLayout.ARM, A("arm")),
		new NameRule(PackedLayout.ORM, A("orm")),
		new NameRule(PackedLayout.RMA, A("rma")),
		new NameRule(PackedLayout.MRA, A("mra"))
	};

	private static string[] A(params string[] words) { return words; }

	[MenuItem(MenuPath, true)]
	private static bool ValidateCreateMaterials() {
		return Selection.GetFiltered<Texture2D>(SelectionMode.DeepAssets).Length > 0;
	}

	[MenuItem(MenuPath)]
	public static void CreateMaterials() {
		Texture2D[] selected = Selection.GetFiltered<Texture2D>(SelectionMode.DeepAssets);
		Shader shader = Shader.Find("Universal Render Pipeline/Lit");

		if (shader == null) {
			EditorUtility.DisplayDialog("URP Lit shader not found",
				"Install and activate the Universal Render Pipeline before creating materials.", "OK");
			return;
		}

		List<TextureSet> sets = BuildTextureSets(selected);
		if (sets.Count == 0) {
			EditorUtility.DisplayDialog("No recognized texture sets",
				"Select textures or folders containing named PBR maps such as albedo, normal, roughness, AO, metalness, or opacity.", "OK");
			return;
		}

		int created = 0;
		var failures = new List<string>();
		try {
			for (int i = 0; i < sets.Count; i++) {
				TextureSet set = sets[i];
				EditorUtility.DisplayProgressBar("Create URP materials", set.DisplayName, (float)i / sets.Count);
				try {
					ConfigureSourceImporters(set);
					CreateOrUpdateMaterial(set, shader);
					created++;
				} catch (Exception exception) {
					failures.Add(set.DisplayName + ": " + exception.Message);
					Debug.LogException(exception);
				}
			}
		} finally {
			EditorUtility.ClearProgressBar();
			AssetDatabase.SaveAssets();
			AssetDatabase.Refresh();
		}

		//string message = "Created or updated " + created + " URP material" + (created == 1 ? "." : "s.");
		//if (failures.Count > 0)
		//	message += "\n\nFailed:\n" + string.Join("\n", failures.ToArray());
		//EditorUtility.DisplayDialog("URP material creation complete", message, "OK");
	}

	private static List<TextureSet> BuildTextureSets(IEnumerable<Texture2D> textures) {
		var sets = new Dictionary<string, TextureSet>(StringComparer.OrdinalIgnoreCase);
		List<Texture2D> textureList = textures.Where(t => t != null).ToList();
		bool allowSingleTextureFallback = textureList.Count == 1;

		foreach (Texture2D texture in textureList) {
			string path = AssetDatabase.GetAssetPath(texture).Replace('\\', '/');
			if (string.IsNullOrEmpty(path) || IsOutputFolder(path))
				continue;

			MapInfo info;
			if (!TryParseName(texture, path, out info)) {
				if (!allowSingleTextureFallback)
					continue;
				info = CreateSingleTextureInfo(texture, path);
			}

			string setId = info.Directory + "|" + info.Key;
			TextureSet set;
			if (!sets.TryGetValue(setId, out set)) {
				set = new TextureSet {
					Key = info.Key,
					DisplayName = info.DisplayName,
					Directory = info.Directory
				};
				sets.Add(setId, set);
			}

			MapInfo old;
			if (!set.Maps.TryGetValue(info.Kind, out old) || IsBetterCandidate(info, old))
				set.Maps[info.Kind] = info;
		}

		List<TextureSet> result = sets.Values.OrderBy(s => s.Directory).ThenBy(s => s.Key).ToList();
		InheritVariantMaps(result);
		return result;
	}

	private static MapInfo CreateSingleTextureInfo(Texture2D texture, string path) {
		string baseName = Path.GetFileNameWithoutExtension(path);
		string key = Regex.Replace(baseName.ToLowerInvariant(), "[^a-z0-9]+", "_").Trim('_');
		if (string.IsNullOrEmpty(key))
			key = "material";

		return new MapInfo {
			Texture = texture,
			Kind = MapKind.Albedo,
			Key = key,
			DisplayName = baseName,
			Directory = Path.GetDirectoryName(path).Replace('\\', '/'),
			Layout = PackedLayout.None,
			NormalConvention = NormalConvention.Unknown
		};
	}

	private static bool IsOutputFolder(string path) {
		string parent = Path.GetFileName(Path.GetDirectoryName(path));
		return string.Equals(parent, MaterialsFolderName, StringComparison.OrdinalIgnoreCase) ||
			   string.Equals(parent, GeneratedFolderName, StringComparison.OrdinalIgnoreCase);
	}

	private static bool TryParseName(Texture2D texture, string path, out MapInfo info) {
		info = null;
		string rawName = Path.GetFileNameWithoutExtension(path);
		string tokenized = Regex.Replace(rawName, "([a-z])([A-Z])", "$1_$2");
		string[] tokens = Regex.Split(tokenized.ToLowerInvariant(), "[^a-z0-9]+").Where(t => t.Length > 0).ToArray();
		if (tokens.Length == 0)
			return false;

		NameRule bestRule = null;
		int bestStart = -1;
		int bestLength = -1;
		int bestEnd = -1;

		foreach (NameRule rule in Rules) {
			foreach (string[] alias in rule.Aliases) {
				for (int start = tokens.Length - alias.Length; start >= 0; start--) {
					if (!TokensMatch(tokens, start, alias))
						continue;

					// Prefer the tag ending furthest right. At the same endpoint,
					// "base color" wins over just "color", and "normal gl" over "gl".
					int end = start + alias.Length;
					if (end > bestEnd || (end == bestEnd && alias.Length > bestLength)) {
						bestRule = rule;
						bestStart = start;
						bestLength = alias.Length;
						bestEnd = end;
					}
					break;
				}
			}
		}

		if (bestRule == null)
			return false;

		var baseTokens = new List<string>();
		for (int i = 0; i < tokens.Length; i++) {
			if (i >= bestStart && i < bestStart + bestLength)
				continue;
			if (!IsTechnicalToken(tokens[i]))
				baseTokens.Add(tokens[i]);
		}

		if (baseTokens.Count == 0)
			baseTokens.Add("material");

		string key = string.Join("_", baseTokens.ToArray());
		info = new MapInfo {
			Texture = texture,
			Kind = bestRule.Kind,
			Key = key,
			DisplayName = MakeDisplayName(baseTokens),
			Directory = Path.GetDirectoryName(path).Replace('\\', '/'),
			Layout = bestRule.Layout,
			NormalConvention = DetectNormalConvention(bestRule.Kind, tokens)
		};
		return true;
	}

	private static NormalConvention DetectNormalConvention(MapKind kind, string[] tokens) {
		if (kind != MapKind.Normal)
			return NormalConvention.Unknown;
		if (tokens.Contains("dx") || tokens.Contains("dxn") || tokens.Contains("directx") ||
			HasTokenSequence(tokens, "direct", "x"))
			return NormalConvention.DirectX;
		if (tokens.Contains("gl") || tokens.Contains("ogl") || tokens.Contains("opengl") ||
			HasTokenSequence(tokens, "open", "gl"))
			return NormalConvention.OpenGL;
		return NormalConvention.Unknown;
	}

	private static bool HasTokenSequence(string[] tokens, string first, string second) {
		for (int i = 0; i < tokens.Length - 1; i++)
			if (tokens[i] == first && tokens[i + 1] == second)
				return true;
		return false;
	}

	private static bool TokensMatch(string[] tokens, int start, string[] alias) {
		if (start < 0 || start + alias.Length > tokens.Length)
			return false;
		for (int i = 0; i < alias.Length; i++)
			if (tokens[start + i] != alias[i])
				return false;
		return true;
	}

	private static bool IsTechnicalToken(string token) {
		return Regex.IsMatch(token, "^(1|2|4|8|16)k$") ||
			   Regex.IsMatch(token, "^v[0-9]+$") ||
			   token == "jpg" || token == "jpeg" || token == "png" || token == "tga" ||
			   token == "tif" || token == "tiff" || token == "exr" || token == "hdr";
	}

	private static string MakeDisplayName(List<string> tokens) {
		string joined = string.Join("_", tokens.ToArray());
		string nicified = ObjectNames.NicifyVariableName(joined);
		return CultureInfo.InvariantCulture.TextInfo.ToTitleCase(nicified.ToLowerInvariant());
	}

	private static bool IsBetterCandidate(MapInfo candidate, MapInfo current) {
		int candidateScore = CandidateScore(candidate.Texture);
		int currentScore = CandidateScore(current.Texture);
		if (candidateScore != currentScore)
			return candidateScore > currentScore;
		return candidate.Texture.width * candidate.Texture.height > current.Texture.width * current.Texture.height;
	}

	private static int CandidateScore(Texture2D texture) {
		string extension = Path.GetExtension(AssetDatabase.GetAssetPath(texture)).ToLowerInvariant();
		switch (extension) {
			case ".exr": return 5;
			case ".tif":
			case ".tiff": return 4;
			case ".tga":
			case ".png": return 3;
			case ".jpg":
			case ".jpeg": return 2;
			default: return 1;
		}
	}

	private static void InheritVariantMaps(List<TextureSet> sets) {
		foreach (TextureSet set in sets) {
			TextureSet parent = sets
				.Where(p => p != set && p.Directory == set.Directory && set.Key.StartsWith(p.Key + "_", StringComparison.OrdinalIgnoreCase))
				.OrderByDescending(p => p.Key.Length)
				.FirstOrDefault();
			if (parent == null)
				continue;

			foreach (KeyValuePair<MapKind, MapInfo> pair in parent.Maps)
				if (pair.Key != MapKind.Albedo && !set.Maps.ContainsKey(pair.Key))
					set.Maps.Add(pair.Key, pair.Value);
		}
	}

	private static void ConfigureSourceImporters(TextureSet set) {
		foreach (MapInfo map in set.Maps.Values.Distinct()) {
			string path = AssetDatabase.GetAssetPath(map.Texture);
			TextureImporter importer = AssetImporter.GetAtPath(path) as TextureImporter;
			if (importer == null)
				continue;

			bool changed = false;
			if (map.Kind == MapKind.Normal) {
				// A mismatched source is read as raw color later, converted into
				// Generated Textures, and that generated normal is assigned instead.
				if (!NeedsNormalConversion(map) && importer.textureType != TextureImporterType.NormalMap) {
					importer.textureType = TextureImporterType.NormalMap;
					changed = true;
				}
				if (!NeedsNormalConversion(map) && importer.flipGreenChannel) {
					importer.flipGreenChannel = false;
					changed = true;
				}
			} else {
				bool shouldBeSrgb = map.Kind == MapKind.Albedo || map.Kind == MapKind.Emission || map.Kind == MapKind.Specular;
				if (importer.sRGBTexture != shouldBeSrgb) {
					importer.sRGBTexture = shouldBeSrgb;
					changed = true;
				}
			}

			if (changed)
				importer.SaveAndReimport();

			// Reimport can replace the native texture object; keep the set pointed
			// at the current asset before any channel packing reads it.
			map.Texture = AssetDatabase.LoadAssetAtPath<Texture2D>(path);
		}
	}

	private static bool NeedsNormalConversion(MapInfo normal) {
		return normal != null &&
			   normal.NormalConvention != NormalConvention.Unknown &&
			   normal.NormalConvention != TargetNormalConvention;
	}

	private static void CreateOrUpdateMaterial(TextureSet set, Shader shader) {
		string materialsFolder = EnsureFolder(set.Directory, MaterialsFolderName);
		string generatedFolder = EnsureFolder(set.Directory, GeneratedFolderName);
		string safeName = SanitizeFileName(set.DisplayName);
		string materialPath = materialsFolder + "/" + safeName + ".mat";

		Material material = AssetDatabase.LoadAssetAtPath<Material>(materialPath);
		if (material == null) {
			material = new Material(shader) { name = set.DisplayName };
			AssetDatabase.CreateAsset(material, materialPath);
		} else {
			material.shader = shader;
			material.name = set.DisplayName;
		}

		PixelSource ao = FindSource(set, MapKind.Occlusion);
		PixelSource roughness = FindSource(set, MapKind.Roughness);
		PixelSource metallic = FindSource(set, MapKind.Metallic);
		PixelSource specular = FindSource(set, MapKind.Specular);
		bool metallicWorkflow = metallic.Exists;

		Texture2D baseMap = set.Get(MapKind.Albedo) != null ? set.Get(MapKind.Albedo).Texture : null;
		MapInfo opacity = set.Get(MapKind.Opacity);
		if (opacity != null) {
			baseMap = WriteBaseOpacity(set, baseMap, opacity.Texture, generatedFolder, safeName, out bool cutout);
			ConfigureTransparency(material, cutout);
		} else {
			ConfigureOpaque(material);
		}

		SetTexture(material, "_BaseMap", baseMap);
		SetTexture(material, "_MainTex", baseMap);
		material.SetColor("_BaseColor", Color.white);
		material.SetColor("_Color", Color.white);

		MapInfo normal = set.Get(MapKind.Normal);
		Texture2D normalTexture = normal != null
			? GetTargetNormal(normal, generatedFolder, safeName)
			: null;
		SetTexture(material, "_BumpMap", normalTexture);
		SetKeyword(material, "_NORMALMAP", normalTexture != null);

		material.SetFloat("_WorkflowMode", metallicWorkflow ? 1f : 0f);
		material.SetFloat("_SmoothnessTextureChannel", 0f);
		material.SetFloat("_Smoothness", 1f);

		if (metallicWorkflow) {
			Texture2D urpMask = WriteUrpMask(set, ao, roughness, metallic, generatedFolder, safeName);
			SetTexture(material, "_MetallicGlossMap", urpMask);
			SetTexture(material, "_OcclusionMap", ao.Exists ? urpMask : null);
			SetTexture(material, "_SpecGlossMap", null);
			material.SetFloat("_Metallic", 1f);
			SetKeyword(material, "_METALLICSPECGLOSSMAP", true);
		} else {
			Texture2D specGloss = (roughness.Exists || specular.Exists)
				? WriteSpecularSmoothness(set, roughness, specular, generatedFolder, safeName)
				: null;
			Texture2D occlusion = ao.Exists ? WriteOcclusion(set, ao, generatedFolder, safeName) : null;
			SetTexture(material, "_SpecGlossMap", specGloss);
			SetTexture(material, "_OcclusionMap", occlusion);
			SetTexture(material, "_MetallicGlossMap", null);
			material.SetColor("_SpecColor", new Color(0.2f, 0.2f, 0.2f, 1f));
			SetKeyword(material, "_METALLICSPECGLOSSMAP", specGloss != null);
		}

		SetKeyword(material, "_OCCLUSIONMAP", material.GetTexture("_OcclusionMap") != null);

		MapInfo emission = set.Get(MapKind.Emission);
		SetTexture(material, "_EmissionMap", emission != null ? emission.Texture : null);
		material.SetColor("_EmissionColor", emission != null ? Color.white : Color.black);
		SetKeyword(material, "_EMISSION", emission != null);
		material.globalIlluminationFlags = emission != null
			? MaterialGlobalIlluminationFlags.BakedEmissive
			: MaterialGlobalIlluminationFlags.EmissiveIsBlack;

		EditorUtility.SetDirty(material);
	}

	private static PixelSource FindSource(TextureSet set, MapKind kind) {
		MapInfo direct = set.Get(kind);
		if (direct != null)
			return new PixelSource { Map = direct, Channel = SourceChannel.Red, Invert = kind == MapKind.Smoothness };

		if (kind == MapKind.Roughness) {
			MapInfo smooth = set.Get(MapKind.Smoothness);
			if (smooth != null)
				return new PixelSource { Map = smooth, Channel = SourceChannel.Red, Invert = true };
		}

		MapInfo packed = set.Get(MapKind.Packed);
		if (packed == null)
			return new PixelSource();

		SourceChannel channel;
		if (TryGetPackedChannel(packed.Layout, kind, out channel))
			return new PixelSource { Map = packed, Channel = channel, Invert = false };
		return new PixelSource();
	}

	private static bool TryGetPackedChannel(PackedLayout layout, MapKind kind, out SourceChannel channel) {
		channel = SourceChannel.Red;
		switch (layout) {
			case PackedLayout.ARM:
			case PackedLayout.ORM:
				if (kind == MapKind.Occlusion) channel = SourceChannel.Red;
				else if (kind == MapKind.Roughness) channel = SourceChannel.Green;
				else if (kind == MapKind.Metallic) channel = SourceChannel.Blue;
				else return false;
				return true;
			case PackedLayout.RMA:
				if (kind == MapKind.Roughness) channel = SourceChannel.Red;
				else if (kind == MapKind.Metallic) channel = SourceChannel.Green;
				else if (kind == MapKind.Occlusion) channel = SourceChannel.Blue;
				else return false;
				return true;
			case PackedLayout.MRA:
				if (kind == MapKind.Metallic) channel = SourceChannel.Red;
				else if (kind == MapKind.Roughness) channel = SourceChannel.Green;
				else if (kind == MapKind.Occlusion) channel = SourceChannel.Blue;
				else return false;
				return true;
			default:
				return false;
		}
	}

	private static Texture2D WriteBaseOpacity(TextureSet set, Texture2D albedo, Texture2D opacity,
		string folder, string safeName, out bool cutout) {
		int width, height;
		GetOutputSize(new[] { albedo, opacity }, out width, out height);
		PixelReader color = albedo != null ? new PixelReader(albedo) : null;
		PixelReader alpha = new PixelReader(opacity);
		var pixels = new Color32[width * height];
		int intermediate = 0;

		for (int y = 0; y < height; y++)
			for (int x = 0; x < width; x++) {
				Color32 c = color != null ? color.Sample(x, y, width, height) : new Color32(255, 255, 255, 255);
				byte a = alpha.Sample(x, y, width, height).r;
				if (a > 12 && a < 243) intermediate++;
				c.a = a;
				pixels[y * width + x] = c;
			}

		cutout = intermediate <= pixels.Length / 20;
		return WritePng(folder + "/" + safeName + "_BaseColorOpacity.png", width, height, pixels, true, true);
	}

	private static Texture2D GetTargetNormal(MapInfo normal, string folder, string safeName) {
		if (!NeedsNormalConversion(normal))
			return normal.Texture;

		string sourcePath = AssetDatabase.GetAssetPath(normal.Texture);
		TextureImporter importer = AssetImporter.GetAtPath(sourcePath) as TextureImporter;
		if (importer == null)
			return normal.Texture;

		TextureImporterType oldType = importer.textureType;
		TextureImporterCompression oldCompression = importer.textureCompression;
		bool oldSrgb = importer.sRGBTexture;
		bool oldReadable = importer.isReadable;
		bool oldFlipGreen = importer.flipGreenChannel;
		Color32[] pixels = null;
		int width = 0;
		int height = 0;

		try {
			// Read the encoded RGB channels without Unity's normal-map swizzle.
			importer.textureType = TextureImporterType.Default;
			importer.textureCompression = TextureImporterCompression.Uncompressed;
			importer.sRGBTexture = false;
			importer.isReadable = true;
			importer.flipGreenChannel = false;
			importer.SaveAndReimport();

			Texture2D raw = AssetDatabase.LoadAssetAtPath<Texture2D>(sourcePath);
			width = raw.width;
			height = raw.height;
			pixels = raw.GetPixels32();
			for (int i = 0; i < pixels.Length; i++)
				pixels[i].g = (byte)(255 - pixels[i].g);
		} finally {
			importer = AssetImporter.GetAtPath(sourcePath) as TextureImporter;
			if (importer != null) {
				importer.textureType = oldType;
				importer.textureCompression = oldCompression;
				importer.sRGBTexture = oldSrgb;
				importer.isReadable = oldReadable;
				importer.flipGreenChannel = oldFlipGreen;
				importer.SaveAndReimport();
			}
		}

		string convention = TargetNormalConvention == NormalConvention.DirectX ? "DX" : "GL";
		string outputPath = folder + "/" + safeName + "_Normal" + convention + ".png";
		Texture2D output = WritePng(outputPath, width, height, pixels, false, false);
		TextureImporter outputImporter = AssetImporter.GetAtPath(outputPath) as TextureImporter;
		if (outputImporter != null) {
			outputImporter.textureType = TextureImporterType.NormalMap;
			outputImporter.sRGBTexture = false;
			outputImporter.flipGreenChannel = false;
			outputImporter.SaveAndReimport();
		}
		return AssetDatabase.LoadAssetAtPath<Texture2D>(outputPath);
	}

	private static Texture2D WriteUrpMask(TextureSet set, PixelSource ao, PixelSource roughness, PixelSource metallic,
		string folder, string safeName) {
		int width, height;
		GetOutputSize(GetTextures(ao, roughness, metallic), out width, out height);
		PixelReaderCache readers = new PixelReaderCache();
		var pixels = new Color32[width * height];
		for (int y = 0; y < height; y++)
			for (int x = 0; x < width; x++) {
				byte rough = Sample(readers, roughness, x, y, width, height, 128);
				pixels[y * width + x] = new Color32(
					Sample(readers, metallic, x, y, width, height, 0),
					Sample(readers, ao, x, y, width, height, 255), 0, (byte)(255 - rough));
			}
		return WritePng(folder + "/" + safeName + "_URPMask.png", width, height, pixels, false, true);
	}

	private static Texture2D WriteSpecularSmoothness(TextureSet set, PixelSource roughness, PixelSource specular,
		string folder, string safeName) {
		int width, height;
		GetOutputSize(GetTextures(roughness, specular), out width, out height);
		PixelReaderCache readers = new PixelReaderCache();
		var pixels = new Color32[width * height];
		for (int y = 0; y < height; y++)
			for (int x = 0; x < width; x++) {
				Color32 spec = specular.Exists
				? readers.Get(specular.Map.Texture).Sample(x, y, width, height)
				: new Color32(51, 51, 51, 255);
				byte rough = Sample(readers, roughness, x, y, width, height, 128);
				pixels[y * width + x] = new Color32(spec.r, spec.g, spec.b, (byte)(255 - rough));
			}
		return WritePng(folder + "/" + safeName + "_SpecularSmoothness.png", width, height, pixels, true, true);
	}

	private static Texture2D WriteOcclusion(TextureSet set, PixelSource ao, string folder, string safeName) {
		int width, height;
		GetOutputSize(GetTextures(ao), out width, out height);
		PixelReaderCache readers = new PixelReaderCache();
		var pixels = new Color32[width * height];
		for (int y = 0; y < height; y++)
			for (int x = 0; x < width; x++) {
				byte value = Sample(readers, ao, x, y, width, height, 255);
				pixels[y * width + x] = new Color32(value, value, value, 255);
			}
		return WritePng(folder + "/" + safeName + "_Occlusion.png", width, height, pixels, false, false);
	}

	private static IEnumerable<Texture2D> GetTextures(params PixelSource[] sources) {
		return sources.Where(s => s.Exists).Select(s => s.Map.Texture).Distinct();
	}

	private static byte Sample(PixelReaderCache readers, PixelSource source, int x, int y,
		int width, int height, byte fallback) {
		if (!source.Exists)
			return fallback;
		Color32 color = readers.Get(source.Map.Texture).Sample(x, y, width, height);
		byte value;
		switch (source.Channel) {
			case SourceChannel.Green: value = color.g; break;
			case SourceChannel.Blue: value = color.b; break;
			case SourceChannel.Alpha: value = color.a; break;
			default: value = color.r; break;
		}
		return source.Invert ? (byte)(255 - value) : value;
	}

	private sealed class PixelReaderCache {
		private readonly Dictionary<Texture2D, PixelReader> readers = new Dictionary<Texture2D, PixelReader>();
		public PixelReader Get(Texture2D texture) {
			PixelReader reader;
			if (!readers.TryGetValue(texture, out reader)) {
				reader = new PixelReader(texture);
				readers.Add(texture, reader);
			}
			return reader;
		}
	}

	private sealed class PixelReader {
		private readonly int width;
		private readonly int height;
		private readonly Color32[] pixels;

		public PixelReader(Texture2D texture) {
			width = texture.width;
			height = texture.height;
			string path = AssetDatabase.GetAssetPath(texture);
			TextureImporter importer = AssetImporter.GetAtPath(path) as TextureImporter;
			bool restoreReadable = importer != null && !importer.isReadable;
			if (restoreReadable) {
				importer.isReadable = true;
				importer.SaveAndReimport();
			}

			Texture2D readable = AssetDatabase.LoadAssetAtPath<Texture2D>(path);
			pixels = readable.GetPixels32();

			if (restoreReadable) {
				importer = AssetImporter.GetAtPath(path) as TextureImporter;
				importer.isReadable = false;
				importer.SaveAndReimport();
			}
		}

		public Color32 Sample(int x, int y, int outputWidth, int outputHeight) {
			float u = outputWidth <= 1 ? 0f : (float)x / (outputWidth - 1);
			float v = outputHeight <= 1 ? 0f : (float)y / (outputHeight - 1);
			float sx = u * (width - 1);
			float sy = v * (height - 1);
			int x0 = Mathf.FloorToInt(sx);
			int y0 = Mathf.FloorToInt(sy);
			int x1 = Mathf.Min(x0 + 1, width - 1);
			int y1 = Mathf.Min(y0 + 1, height - 1);
			float tx = sx - x0;
			float ty = sy - y0;
			Color a = Color32.Lerp(pixels[y0 * width + x0], pixels[y0 * width + x1], tx);
			Color b = Color32.Lerp(pixels[y1 * width + x0], pixels[y1 * width + x1], tx);
			return (Color32)Color.Lerp(a, b, ty);
		}
	}

	private static void GetOutputSize(IEnumerable<Texture2D> textures, out int width, out int height) {
		Texture2D largest = textures.Where(t => t != null)
			.OrderByDescending(t => (long)t.width * t.height).FirstOrDefault();
		width = largest != null ? largest.width : 4;
		height = largest != null ? largest.height : 4;
	}

	private static Texture2D WritePng(string path, int width, int height, Color32[] pixels,
		bool sRgb, bool hasAlpha) {
		var output = new Texture2D(width, height, TextureFormat.RGBA32, false, !sRgb);
		output.SetPixels32(pixels);
		output.Apply(false, false);
		File.WriteAllBytes(path, output.EncodeToPNG());
		Object.DestroyImmediate(output);

		AssetDatabase.ImportAsset(path, ImportAssetOptions.ForceUpdate);
		TextureImporter importer = AssetImporter.GetAtPath(path) as TextureImporter;
		if (importer != null) {
			importer.textureType = TextureImporterType.Default;
			importer.sRGBTexture = sRgb;
			importer.alphaSource = hasAlpha ? TextureImporterAlphaSource.FromInput : TextureImporterAlphaSource.None;
			importer.alphaIsTransparency = hasAlpha && sRgb;
			importer.mipmapEnabled = true;
			importer.isReadable = false;
			importer.textureCompression = TextureImporterCompression.CompressedHQ;
			importer.SaveAndReimport();
		}
		return AssetDatabase.LoadAssetAtPath<Texture2D>(path);
	}

	private static string EnsureFolder(string parent, string child) {
		string path = parent + "/" + child;
		if (!AssetDatabase.IsValidFolder(path))
			AssetDatabase.CreateFolder(parent, child);
		return path;
	}

	private static string SanitizeFileName(string value) {
		foreach (char invalid in Path.GetInvalidFileNameChars())
			value = value.Replace(invalid, '_');
		return value.Trim();
	}

	private static void SetTexture(Material material, string property, Texture texture) {
		if (material.HasProperty(property))
			material.SetTexture(property, texture);
	}

	private static void SetKeyword(Material material, string keyword, bool enabled) {
		if (enabled) material.EnableKeyword(keyword);
		else material.DisableKeyword(keyword);
	}

	private static void ConfigureOpaque(Material material) {
		material.SetFloat("_Surface", 0f);
		material.SetFloat("_AlphaClip", 0f);
		material.SetFloat("_SrcBlend", (float)BlendMode.One);
		material.SetFloat("_DstBlend", (float)BlendMode.Zero);
		material.SetFloat("_ZWrite", 1f);
		material.SetOverrideTag("RenderType", "Opaque");
		material.renderQueue = (int)RenderQueue.Geometry;
		SetKeyword(material, "_SURFACE_TYPE_TRANSPARENT", false);
		SetKeyword(material, "_ALPHATEST_ON", false);
	}

	private static void ConfigureTransparency(Material material, bool cutout) {
		if (cutout) {
			ConfigureOpaque(material);
			material.SetFloat("_AlphaClip", 1f);
			material.SetFloat("_Cutoff", 0.5f);
			material.SetOverrideTag("RenderType", "TransparentCutout");
			material.renderQueue = (int)RenderQueue.AlphaTest;
			SetKeyword(material, "_ALPHATEST_ON", true);
			return;
		}

		material.SetFloat("_Surface", 1f);
		material.SetFloat("_Blend", 0f);
		material.SetFloat("_AlphaClip", 0f);
		material.SetFloat("_SrcBlend", (float)BlendMode.SrcAlpha);
		material.SetFloat("_DstBlend", (float)BlendMode.OneMinusSrcAlpha);
		material.SetFloat("_ZWrite", 0f);
		material.SetOverrideTag("RenderType", "Transparent");
		material.renderQueue = (int)RenderQueue.Transparent;
		SetKeyword(material, "_SURFACE_TYPE_TRANSPARENT", true);
		SetKeyword(material, "_ALPHATEST_ON", false);
	}
}